
<p><?php echo $this->translate('partner-create intro text'); ?></p>
<p><b><?php echo $this->translate('partner-create current publisher quota status text')?></b><?php echo $this->publisherQuota . " ". $this->translate('partner-create publisher quota test part 1') . " " .$this->remainingPublishers . $this->translate('partner-create publisher quota test part 2') . " "?>
<?php echo " ".$this->translate('partner-create publisher quota test part 3')?><a href="http://corp.kaltura.com/company/contact-us"><?php echo $this->translate('contact kaltura')?></a><?php echo " ". $this->translate('partner-create publisher quota test part 4')?></p>
<?php echo $this->form; ?>