<script type="text/javascript">
	<?php require_once('dynamic-metadata-fields.js'); ?>

	$(function() {

		if ($('.field-config-row').size() > 0) { // the form is not initalized when creating new profile and when there is an error
			new $.distributionMetadataDynamicFields({
				fields: ['RELATED_LINK_N_URL', 'RELATED_LINK_N_TITLE'],
				buttonText: 'Add Related Link'
			});

			new $.distributionMetadataDynamicFields({
				fields: ['TAGS_PREMIUM_N_MARKET', 'TAGS_PREMIUM_N_NAMESPACE', 'TAGS_PREMIUM_N_VALUE'],
				buttonText: 'Add Premium Tag'
			});
		}
	});
</script>