<?php
/**
 * @package plugins.tvinciDistribution
 * @subpackage model.enum
 */ 
interface TvinciDistributionField extends BaseEnum
{
	const MEDIA_TITLE  					= 'MEDIA_TITLE';
	const MEDIA_DESCRIPTION  			= 'MEDIA_DESCRIPTION';

	const ACTIVATE_PUBLISHING			= 'ACTIVATE_PUBLISHING';
	const MEDIA_TYPE					= 'MEDIA_TYPE';

	const GEO_BLOCK_RULE 				= 'GEO_BLOCK_RULE';
	const WATCH_PERMISSIONS_RULE		= 'WATCH_PERMISSIONS_RULE';

	const LANGUAGE						= 'LANGUAGE';

	const START_DATE					= 'START_DATE';
	const END_DATE						= 'END_DATE';
	const CATALOG_START_DATE			= 'CATALOG_START_DATE';
	const CATALOG_END_DATE				= 'CATALOG_END_DATE';

	const METADATA_RUNTIME				= 'METADATA_RUNTIME';
	const METADATA_RELEASE_YEAR			= 'METADATA_RELEASE_YEAR';
	const METADATA_RELEASE_DATE			= 'METADATA_RELEASE_DATE';
	const METADATA_GENRE				= 'METADATA_GENRE';
	const METADATA_SUB_GENRE			= 'METADATA_SUB_GENRE';
	const METADATA_RATING				= 'METADATA_RATING';
	const METADATA_COUNTRY				= 'METADATA_COUNTRY';
	const METADATA_CAST					= 'METADATA_CAST';
	const METADATA_DIRECTOR				= 'METADATA_DIRECTOR';
	const METADATA_AUDIO_LANGUAGE		= 'METADATA_AUDIO_LANGUAGE';
	const METADATA_STUDIO				= 'METADATA_STUDIO';
}