<?php
/**
 * @package plugins.freewheelGenericDistribution
 * @subpackage model.enum
 */ 
interface FreewheelGenericDistributionField extends BaseEnum
{
	const VIDEO_ID						= 'VIDEO_ID';
	
	// fwTitles
	const FWTITLES_EPISODE_TITLE1		= 'FWTITLES_EPISODE_TITLE1';
	const FWTITLES_EPISODE_TITLE2		= 'FWTITLES_EPISODE_TITLE2';
	const FWTITLES_SERIES				= 'FWTITLES_SERIES';
	const FWTITLES_SEASON				= 'FWTITLES_SEASON';
	const FWTITLES_GROUP1				= 'FWTITLES_GROUP1';
	const FWTITLES_GROUP2				= 'FWTITLES_GROUP2';
	const FWTITLES_GROUP3				= 'FWTITLES_GROUP3';
	const FWTITLES_GROUP4				= 'FWTITLES_GROUP4';
	const FWTITLES_GROUP5				= 'FWTITLES_GROUP5';
	const FWTITLES_GROUP6				= 'FWTITLES_GROUP6';
	const FWTITLES_GROUP7				= 'FWTITLES_GROUP7';
	const FWTITLES_GROUP8				= 'FWTITLES_GROUP8';
	const FWTITLES_GROUP9				= 'FWTITLES_GROUP9';
	const FWTITLES_GROUP10				= 'FWTITLES_GROUP10';
	
	// fwDescriptions 
	const FWDESCRIPTIONS_SERIES			= 'FWDESCRIPTIONS_SERIES';
	const FWDESCRIPTIONS_EPISODE		= 'FWDESCRIPTIONS_EPISODE';
	
	const GENRE							= 'GENRE';
	const RATING						= 'RATING';
	const DATE_AVAILABLE_START			= 'DATE_AVAILABLE_START';
	const DATE_AVAILABLE_END			= 'DATE_AVAILABLE_END';
	const DATE_ISSUED					= 'DATE_ISSUED';
	const DATE_LAST_AIRED				= 'DATE_LAST_AIRED';
	const DURATION						= 'DURATION';
	
	const FWMETADATA					= 'FWMETADATA';
}