<?php 
    $this->headScript() ->appendFile($this->baseUrl('js/excanvas.compiled.js'))
                        ->appendFile($this->baseUrl('js/jquery.corner.js')); 
?>
<div class="box">

            <p>
                <?php echo $this->translate('please wait....'); ?>
            </p>
            <?php echo $this->form; ?>

</div>
<script>


    function getTimeOffset() {
		var d = new Date();
		return d.getTimezoneOffset();
    }
    
    jQuery(function() {
        $("#timezone_offset").val(getTimeOffset());
    });
</script>