
<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div>
<?php endif; ?>

<?php echo $this->form ?>
<script type="text/javascript">

var newThumbDimensionsIndex = 0;

function newThumbDimensions() {
	var newThumbDimensionsTemplate = jQuery(".newThumbDimensions:last");
	var newThumbDimensionsForm = newThumbDimensionsTemplate.clone();
	newThumbDimensionsForm.removeClass("newThumbDimensions");
	newThumbDimensionsForm.find('[name="dimensionsWidth"]').attr('name', 'dimensionsWidth[' + newThumbDimensionsIndex + ']');
	newThumbDimensionsForm.find('[name="dimensionsHeight"]').attr('name', 'dimensionsHeight[' + newThumbDimensionsIndex + ']');
	newThumbDimensionsForm.find('[name="dimensionsRequired"]').attr('name', 'dimensionsRequired[' + newThumbDimensionsIndex + ']');
	newThumbDimensionsTemplate.after(newThumbDimensionsForm);
	newThumbDimensionsForm.show();

	newThumbDimensionsIndex++;
}

function removeThumbDimensions(index){
	jQuery(".thumbDimensions_" + index).remove();
}

function actionEnabledChanged(action){
	var enabled = jQuery("." + action + "-enabled :checked").size();
	var fields = jQuery(".action-fields-" + action);
	if(enabled)
		fields.show();
	else
		fields.hide();
}

function actionFileClicked(action, file){
	var dataField = jQuery("." + file + "-" + action + "-data");
	if(!dataField.size())
		return false;
	
	var data = dataField.val();
	
	jQuery('#file-view-dialog').remove();
	dialogDiv = jQuery('<div id="file-view-dialog"/>temp</div>').appendTo('body');
	dialogDiv.text(data);
	
	dialogDiv.dialog({
		bgiframe: true,
		modal: true,
		resizable: false,
		width: 400,
		height: 200,
		title: '<?php echo $this->translate('File data'); ?>',
		buttons: {
			'<?php echo $this->translate('Close'); ?>': function() {
				jQuery(this).dialog('close');
			}
		},
		close: function() {
		}	
	});	
	dialogDiv.load();
	
	return false;
}

function actionFileLoaded(action, file){
	var dataField = jQuery("." + file + "-" + action + "-data");
	if(!dataField.size())
		return false;

	var link = jQuery("." + file + "-" + action + "-label");
	if(!link.size())
		return false;

	link.click(function(){
		actionFileClicked(action, file);
		return false;
	});
	link.wrap('<a href="#"/>');
}

function actionLoaded(action){
	actionEnabledChanged(action);
	actionFileLoaded(action, "mrssTransformer");
	actionFileLoaded(action, "mrssValidator");
	actionFileLoaded(action, "resultsTransformer");
}

jQuery(function() {

	actionLoaded("submit");
	actionLoaded("update");
	actionLoaded("delete");
	actionLoaded("fetchReport");
});


</script>