<?php

class KalturaVerizonCategoryMapping
{
	private static $verizonCatMappings = array(
'College BK News' => 'FSPORTS_COLLHOOPS',
'Action_Fuel' => 'FSPORTS_FUEL',
'Motorsports_Speed' => 'FSPORTS_SPEED',
'Top News' => 'FSPORTS_TOPNEWS',
'Features' => 'FSPORTS_FEATURES',
'Baseball News' => 'FSPORTS_MLB',
'NBA News' => 'FSPORTS_NBA',
'College FB News' => 'FSPORTS_COLLFOOTBALL',
'Hockey News' => 'FSPORTS_NHL',
'NFL News' => 'FSPORTS_NFL',
'More Fox Sports' => 'FSPORTS_MORE',
'Motorsports' => 'FSPORTS_NASCAR',
'Action Sports' => 'FSPORTS_ACTION',
'Soccer_FSC' => 'FSPORTS_SOCCER',
'Golf' => 'FSPORTS_GOLF',
'NCAA_Tourney' => 'FSPORTS_COLLHOOPS',
'AVP Beach Volleyball' => '',
'Fantasy_Video' => 'FSPORTS_FANTASY',
'Horseracing' => 'FSPORTS_MAIN',
'BCS' => 'FSPORTS_BCS',
'Super Bowl Ads' => 'FSPORTS_NFL',
'Daytona 500 Video' => 'FSPORTS_NASCAR',
'Player of the Week' => '',
'Best Damn Sports Show Video' => 'FSPORTS_BESTDAMNSHOW',
'Live Show' => '',
'Fantasy Football House' => '',
'PremierLeague' => 'FSPORTS_SOCCER',
'Olympic Sports' => 'FSPORTS_MORE',
'NFL_Weekly_Leaders' => 'FSPORTS_NFL',
'NFL_Power_Rankings' => 'FSPORTS_NFL',
'Second_Guesses' => 'FSPORTS_NFL',
'Online_OT' => 'FSPORTS_NFL',
'Horrow' => 'FSPORTS_MAIN',
'Fight Video' => 'FSPORTS_BOXMMA',
'Tennis_Week' => 'FSPORTS_MORE',
'Heisman Video' => 'FSPORTS_COLLFOOTBALL',
'Scout' => 'FSPORTS_MAIN',
'College WBK News' => 'FSPORTS_COLLHOOPS',
'Franks picks' => 'FSPORTS_PICKS',
'Show_NFL on Fox' => 'FSPORTS_NFL',
'Show_MLB on Fox' => 'FSPORTS_MLB',
'big12' => 'FSPORTS_MAIN',
'pac10' => 'FSPORTS_MAIN',
'wpt' => 'FSPORTS_MORE',
'NHTSA' => 'FSPORTS_MAIN',
'NFL FOX Wire' => 'FSPORTS_NFL',
'TOTH' => '',
'Jay Glazer' => 'FSPORTS_NFL',
'NFL Preview Recap' => 'FSPORTS_NFL',
'Animated Video' => 'FSPORTS_MORE',
'NASCAR Power Rankings' => 'FSPORTS_NASCAR',
'NASCAR Spotlight Interviews' => 'FSPORTS_NASCAR',
'NASCAR Chase' => 'FSPORTS_NASCAR',
'CFB Fearless Predictions' => '',
'Coaches Corner' => '',
'MLB Fantasy Video' => '',
'afterparty' => 'FSPORTS_MAIN',
'coachspeak' => 'FSPORTS_MAIN',
'collegeexperiment' => 'FSPORTS_MAIN',
'cubed' => 'FSPORTS_MAIN',
'insidecall' => 'FSPORTS_MAIN',
'Fox Sports_no_ad' => '',
'Replay' => 'FSPORTS_MAIN',
'big ten' => 'FSPORTS_MAIN',
'Hoops Hysteria' => '',
'Hoops Hysteria' => 'FSPORTS_COLLHOOPS',
'3wide' => 'FSPORTS_MAIN',
'gmcorner' => 'FSPORTS_MAIN',
'being' => 'FSPORTS_MAIN',
'lunch-leftovers' => '',
'lunch-leftovers' => 'FSPORTS_MAIN',
'lwb_qb' => 'FSPORTS_MAIN',
'golf_ofcourse' => 'FSPORTS_GOLF',
'mlb_cheapseats' => 'FSPORTS_MLB',
'wheelsup' => 'FSPORTS_MORE',
'mmathletics' => 'FSPORTS_MAIN',
'Fox_Flash' => 'FSPORTS_MAIN',
'show_NASCAR on Fox' => 'FSPORTS_NASCAR',
'mlb_highlights' => 'FSPORTS_MLB',
'fullcount' => 'FSPORTS_MLB',
'nba_playoffs' => 'FSPORTS_NBA',
'onthemark' => 'FSPORTS_MAIN',
'scheintakes' => 'FSPORTS_NFL',
'hotcorner_al' => 'FSPORTS_MLB',
'hotcorner_nl' => 'FSPORTS_MLB',
'fantasy_baseball' => '',
'motor_underthehood' => 'FSPORTS_NASCAR',
'draftpreview_nba' => 'FSPORTS_NBA',
'motor_diggerandfriends' => 'FSPORTS_NASCAR',
'nfl_draft' => 'FSPORTS_NFL',
'scheinpicks' => 'FSPORTS_NFL',
'fantasy_football' => '',
'randyhill' => 'FSPORTS_NBA',
'goodman_nba' => 'FSPORTS_NBA',
'nbatipoff' => 'FSPORTS_NBA',
'nbainthepaint' => 'FSPORTS_NBA',
'fantasyfix' => '',
'goodman_cbk' => 'FSPORTS_COLLHOOPS',
'golfweek' => 'FSPORTS_GOLF',
'golfshottv' => 'FSPORTS_GOLF',
'ufc' => 'FSPORTS_BOXMMA',
'fuel_skate' => 'FSPORTS_ACTION',
'fuel_surf' => 'FSPORTS_ACTION',
'fuel_snow' => 'FSPORTS_ACTION',
'fuel_wake' => 'FSPORTS_ACTION',
'bloopers' => 'FSPORTS_MORE',
'girls_hootersdreamgirl' => 'FSPORTS_MAIN',
'girls_shapemag' => 'FSPORTS_MAIN',
'redbull_airraces' => 'FSPORTS_MORE',
'fairgame' => 'FSPORTS_MAIN',
'baseball' => 'FSPORTS_MORE',
'glazer_trainingcamp' => 'FSPORTS_NFL',
'Franks picks_Curts pick' => 'FSPORTS_PICKS',
'NFL Insider' => 'FSPORTS_NFL',
'cosmic_schein' => 'FSPORTS_MAIN',
'online_ot_hilites' => 'FSPORTS_NFL',
);
	public static function getMapping ($key)
	{
		if (isset(self::$verizonCatMappings[$key]))
		{
			return self::$verizonCatMappings[$key];
		}
		
		return null;
	}
};
