<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php if($this->category): ?>

	<p><?php echo $this->translate('category-media-report intro text'); ?></p>
	
	<p class="category-media-report-title">
		<?php echo $this->translate('category-media-report title part-1'); ?>
		<?php echo $this->category->name; ?>
		<?php echo $this->translate('category-media-report title part-2'); ?>
	</p>
	<?php echo $this->filterForm; ?>
	
	<div id="category-media-report-sum" class="clear">
		<table>
			<tr>
				<td>Media Items</td>
				<td>
					<?php echo $this->entriesCount; ?>
					<?php echo $this->translate('category-media-report sum entriesCount'); ?>
				</td>
				<td>
					<?php echo $this->playedEntriesCount; ?>
					<?php echo $this->translate('category-media-report sum playedEntriesCount'); ?>
				</td>
				<td>
					<?php echo $this->entriesPlaysCount; ?>
					<?php echo $this->translate('category-media-report sum entriesPlaysCount'); ?>
				</td>
				<td>
					<?php echo $this->translate('category-media-report sum maxPlaysEntry part-1'); ?>
					<a href="<?php echo $this->url(array('controller' => 'plugin', 'action' => 'CategoryMediaReportAction', 'entryId' => $this->maxPlaysEntryId)); ?>"><?php echo $this->maxPlaysEntryName; ?></a>
					<?php echo $this->translate('category-media-report sum maxPlaysEntry part-2'); ?>
					<?php echo $this->maxPlaysCount; ?>
					<?php echo $this->translate('category-media-report sum maxPlaysEntry part-3'); ?>
				</td>
			</tr>
		</table>
	</div>
	
	<div id="category-media-report-top" class="clear">
		<table>
			<thead>
				<tr>
					<th><?php echo $this->translate('category-media-report-top entry-name'); ?></th>
					<th><?php echo $this->translate('category-media-report-top entry-creatorId'); ?></th>
					<th><?php echo $this->translate('category-media-report-top entry-plays'); ?></th>
					<th><?php echo $this->translate('category-media-report-top entry-minutesViewed'); ?></th>
					<th><?php echo $this->translate('category-media-report-top entry-avgViewTime'); ?></th>
					<th><?php echo $this->translate('category-media-report-top entry-avgDropOff'); ?></th>
				</tr>
			</thead>
			<tfoot>
			<tr>
				<td colspan="6">
				<?php echo $this->paginator; ?>
				</td>
			</tr>
			</tfoot>
			<tbody>
				<?php foreach($this->paginator as $entry): ?>
				<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
					<td><a href="<?php echo $this->url(array('controller' => 'plugin', 'action' => 'CategoryMediaReportAction', 'entryId' => $entry->id)); ?>"><?php echo $entry->name; ?></a></td>
					<td><?php echo $entry->name; ?></td>
					<td><?php echo $entry->plays; ?></td>
					<td><?php echo $entry->minutesViewed; ?></td>
					<td><?php echo $entry->avgViewTime; ?></td>
					<td><?php echo $entry->avgDropOff; ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>

<?php endif; ?>