<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php if($this->category): ?>

	<h2><?php echo $this->translate('category-full-report intro text'); ?></h2>
	
	<p class="category-full-report-title">
		<?php echo $this->translate('category-full-report title part-1'); ?>
		<?php echo $this->category->name; ?>
		<?php echo $this->translate('category-full-report title part-2'); ?>
	</p>
	<?php echo $this->filterForm; ?>

	<?php if($this->paginator): ?>
		<div id="category-full-report-top" class="clear">
			<table>
				<thead>
					<tr>
						<th><?php echo $this->translate('category-full-report-top entry-name'); ?></th>
						<th><?php echo $this->translate('category-full-report-top entry-creatorId'); ?></th>
						<th><?php echo $this->translate('category-full-report-top entry-plays'); ?></th>
						<th><?php echo $this->translate('category-full-report-top entry-minutesViewed'); ?></th>
						<th><?php echo $this->translate('category-full-report-top entry-avgViewTime'); ?></th>
						<th><?php echo $this->translate('category-full-report-top entry-avgDropOff'); ?></th>
					</tr>
				</thead>
				<tfoot>
				<tr>
					<td colspan="6">
					<?php echo $this->paginator; ?>
					</td>
				</tr>
				</tfoot>
				<tbody>
					<?php foreach($this->paginator as $entry): ?>
					<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
						<td><a href="<?php echo $this->url(array('controller' => 'plugin', 'action' => 'CategoryMediaReportAction', 'entryId' => $entry->id)); ?>"><?php echo $entry->name; ?></a></td>
						<td><?php echo $entry->name; ?></td>
						<td><?php echo $entry->plays; ?></td>
						<td><?php echo $entry->minutesViewed; ?></td>
						<td><?php echo $entry->avgViewTime; ?></td>
						<td><?php echo $entry->avgDropOff; ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	<?php endif; ?>
<?php endif; ?>