
<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php if ($this->FormFormat == 'invalid'): ?>
	<script type="text/javascript">
		alert("invalid Form format");
	</script>
<?php endif; ?>

<style type="text/css">
	#configuration-map-configure-dialog{ width:auto ; left: auto}
</style>

<?php echo $this->form ?>

<script type="text/javascript">

	try {
		jQuery(function () {
			<?php if ($this->formValid): ?>
			dialogDiv.dialog('close');
			jQuery('#frmConfigurationMapConfigure').submit();
			<?php endif; ?>
		});
	}
	catch (e) {
	}

</script>