
<p><?php echo $this->translate('drm policy list intro text'); ?></p>
<?php echo $this->filterForm; ?>
<?php echo $this->createForm; ?>
<div id="drm_policy_list_div" class="clear">
	<table>
		<thead>
			<tr>
				<th><?php echo $this->translate('ID'); ?></th>
				<th><?php echo $this->translate('Status'); ?></th>
				<th><?php echo $this->translate('Name'); ?></th>
				<th><?php echo $this->translate('Publisher ID'); ?></th>
				<th><?php echo $this->translate('Provider'); ?></th>
				<th><?php echo $this->translate('Creation Date'); ?></th>
				<th><?php echo $this->translate('Action'); ?></th>
			</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="10">
			<?php echo $this->paginator; ?>
			</td>
		</tr>
		</tfoot>
		<tbody>
			<?php foreach($this->paginator as $obj): ?>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><?php echo $obj->id; ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Drm_Enum_DrmPolicyStatus', $obj->status); ?></td>
				<td><?php echo $obj->name; ?></td>
				<td><?php echo $obj->partnerId; ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Drm_Enum_DrmProviderType', $obj->provider); ?></td>
				<td><?php echo date($this->translate('time format'), $obj->createdAt); ?></td>
				<td>
					<select class="options" onchange="doAction(this.value, <?php echo $obj->id; ?>)">
						<option value=""><?php echo $this->translate('Select Action'); ?></option>
						<option value="configureDrmPolicy" ><?php echo $this->translate('Configure'); ?></option>
						<option value="remove" ><?php echo $this->translate('Remove'); ?></option>
					</select>
				</td>				
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

<script type="text/javascript">

jQuery('#filter_type').change(function() {
	if(this.value == "none") {
		$("#filter_text").css("display","none");
	}
	else {
		$("#filter_text").css("display","inline");
		$("#filter_text input").focus();
	}
});

jQuery('#filter_type').change();

function doAction(action, policyId) {
	if (action && eval('typeof ' + action) == 'function')
	{
		f = eval(action);
		Array.prototype.shift.apply(arguments);
		f.apply(this, arguments);
	}
	jQuery('select.options').val('');
}

function remove(policyId)
{
	var ok = confirm('<?php echo $this->translate('Are you sure you want to remove drm policy ?'); ?>');
	if (ok)
	{
		changeStatus(
            policyId,
			function() {
				alert('<?php echo $this->translate('Drm policy removed');?>');
			}
		);
	}
}

function changeStatus(policyId, callback)
{
	var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'DrmPolicyDeleteAction', 'drmPolicyId' => 'POLICYID')); ?>';
	url = url.replace('POLICYID', policyId);
	jQuery.ajax({
		url: url,
		dataType: 'json',
		success: function(result) {
			if (result != 'ok')
				this.error();
			
			if (callback && (typeof callback == 'function'))
			{
				callback.apply(this);
			}			
			jQuery('#frmPaginator1').submit();
		},
		error: function() {
			alert('<?php echo $this->translate('an error occurred'); ?>');
		}
	});
}


function newDrmPolicy(partnerId, drmProvider)
{
	if(!partnerId.length || isNaN(partnerId)){
		alert('<?php echo $this->translate('Publisher ID not supplied'); ?>');
		return;
	}
	
	if(!drmProvider.length){
		alert('<?php echo $this->translate('Drm provider not supplied'); ?>');
		return;
	}

	paramsStr = '/new_partner_id/' + partnerId + '/new_drm_provider/' + drmProvider;

	loadDrmPolicy(paramsStr);
}

function configureDrmPolicy(policyId)
{
	if(typeof policyId == 'undefined'){
		alert('<?php echo $this->translate('Drm policy ID not supplied'); ?>');
		return;
	}

	policyIdStr = '/drm_policy_id/' + policyId;

    loadDrmPolicy(policyIdStr);
}


function loadDrmPolicy(paramStr)
{	
	var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'DrmPolicyConfigureAction')); ?>' + paramStr;
	
	jQuery('#drm-policy-configure-dialog').remove();
	dialogDiv = jQuery('<div id="drm-policy-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');
	
	dialogDiv.dialog({
		bgiframe: true,
		modal: true,
		resizable: false,
		width: 600,
		height: 600,
		title: '<?php echo $this->translate('Drm Policy'); ?>',
		buttons: {
			'<?php echo $this->translate('Save'); ?>': function() {
				jQuery(this).find('#frmDrmPolicyConfigure').submit();
			},
			'<?php echo $this->translate('Close'); ?>': function() {
				jQuery(this).dialog('close');
			}
		}
	});
	
	dialogDiv.load(
		url, 
		null, 
		function() {
			jQuery(this).find('#frmDrmPolicyConfigure').ajaxForm({
				success: loadDrmPolicySuccess,
				iframe: true
			});
		}
	);
}

function loadDrmPolicySuccess(html) {
	if (jQuery(html).filter('#frmDrmPolicyConfigure').hasClass('valid'))
	{
		dialogDiv.dialog('close');
		if (jQuery('#frmPaginator1').length){
			jQuery('#frmPaginator1').submit();
		}
		else {
			jQuery('#frmPartnerIdFilter').submit();
		}
	}
	jQuery('#frmDrmPolicyConfigure').replaceWith(html);
	jQuery('#frmDrmPolicyConfigure').ajaxForm({
		success: loadDrmPolicySuccess,
		iframe: true
	});
}

</script>
