<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php
	$this->form->setAction($this->url(array('controller' => 'plugin', 'action' => 'DrmAdminApiAction')));
	echo $this->form;
?>

<style type="text/css">
	#frmAdminApiConfigure dl dd input{width: 520px; height: 18px;}
	#frmAdminApiConfigure dt,dd {padding-top: 6px;}
</style>


<script type="text/javascript">


</script>