name: Update BUILD_TIME

on:
  push:
    branches:
      - ${{ github.ref_name }}

jobs:
  update-build-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date and time
        run: echo "Build Time: $(date)" > BUILD_TIME.txt

      - name: Append latest commit hash
        run: echo "Latest Commit: $(git rev-parse HEAD)" >> BUILD_TIME.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add BUILD_TIME.txt
          git commit -m "Update BUILD_TIME.txt with latest build info" || echo "No changes to commit"
          git push
