<?php 
require_once __DIR__ . '/../index/index.phtml';
?>

<script type="text/javascript">
function addSubTitle(subTitle) {
	$("#sub-header").append('<ul class="sub-navigation"><li class="active"><a>' + subTitle + '</a></li></ul>');
}

</script>
<div id="sub-header">
	<?php if (Infra_AuthHelper::getAuthInstance()->hasIdentity()): ?>
		<?php echo $this->navigation()->menu()->renderMenu(null, array(
			'onlyActiveBranch' => true,
			'ulClass' => 'sub-navigation', 
			'minDepth' => 0, 
			'maxDepth' => 1
		)); ?>
	<?php endif; ?>
</div>