GRANT ALL ON *.* TO '@DWH_USER@'@'@DB1_HOST@' IDENTIFIED BY '@DWH_PASS@';
GRANT ALL ON *.* TO '@DWH_USER@'@'%' IDENTIFIED BY '@DWH_PASS@';
GRANT SELECT ON *.* TO 'kaltura_read'@'@DB1_HOST@' IDENTIFIED BY 'kaltura_read';
GRANT SELECT ON @SPHINX_DB_NAME@.* TO '@SPHINX_DB_USER@'@'%' IDENTIFIED BY '@SPHINX_DB_PASS@';
FLUSH privileges;
COMMIT;