insert into `flavor_params` (`id`, `version`, `partner_id`, `name`, `tags`, `description`, `ready_behavior`, `created_at`, `updated_at`, `deleted_at`, `is_default`, `format`, `video_codec`, `video_bitrate`, `audio_codec`, `audio_bitrate`, `audio_channels`, `audio_sample_rate`, `audio_resolution`, `width`, `height`, `frame_rate`, `gop_size`, `two_pass`, `conversion_engines`, `conversion_engines_extra_params`, `custom_data`, `view_order`, `bypass_by_extension`, `creation_mode`)
values(8,'0','0','Basic - Small (H264)','web,mbr','','2',now(),now(),NULL,'1','mp4','h264','400','aac','96','0','0','0','0','352','0','0','0','2','',NULL,'0',NULL,'1');
insert into `flavor_params` (`id`, `version`, `partner_id`, `name`, `tags`, `description`, `ready_behavior`, `created_at`, `updated_at`, `deleted_at`, `is_default`, `format`, `video_codec`, `video_bitrate`, `audio_codec`, `audio_bitrate`, `audio_channels`, `audio_sample_rate`, `audio_resolution`, `width`, `height`, `frame_rate`, `gop_size`, `two_pass`, `conversion_engines`, `conversion_engines_extra_params`, `custom_data`, `view_order`, `bypass_by_extension`, `creation_mode`)
values(9,'0','0','Standard - Small (H264)','web,mbr','','2',now(),now(),NULL,'1','mp4','h264','750','aac','96','0','0','0','0','352','0','0','0','2','',NULL,'0',NULL,'1');
insert into `flavor_params` (`id`, `version`, `partner_id`, `name`, `tags`, `description`, `ready_behavior`, `created_at`, `updated_at`, `deleted_at`, `is_default`, `format`, `video_codec`, `video_bitrate`, `audio_codec`, `audio_bitrate`, `audio_channels`, `audio_sample_rate`, `audio_resolution`, `width`, `height`, `frame_rate`, `gop_size`, `two_pass`, `conversion_engines`, `conversion_engines_extra_params`, `custom_data`, `view_order`, `bypass_by_extension`, `creation_mode`)
values(10,'0','0','Standard - Large (H264)','web,mbr','','2',now(),now(),NULL,'1','mp4','h264','1350','aac','96','0','0','0','0','720','0','0','0','2','',NULL,'0',NULL,'1');
insert into `flavor_params` (`id`, `version`, `partner_id`, `name`, `tags`, `description`, `ready_behavior`, `created_at`, `updated_at`, `deleted_at`, `is_default`, `format`, `video_codec`, `video_bitrate`, `audio_codec`, `audio_bitrate`, `audio_channels`, `audio_sample_rate`, `audio_resolution`, `width`, `height`, `frame_rate`, `gop_size`, `two_pass`, `conversion_engines`, `conversion_engines_extra_params`, `custom_data`, `view_order`, `bypass_by_extension`, `creation_mode`)
values(11,'0','0','High - Large (H264)','web,mbr','','2',now(),now(),NULL,'1','mp4','h264','2500','aac','128','0','0','0','0','720','0','0','0','2','',NULL,'0',NULL,'1');
insert into `flavor_params` (`id`, `version`, `partner_id`, `name`, `tags`, `description`, `ready_behavior`, `created_at`, `updated_at`, `deleted_at`, `is_default`, `format`, `video_codec`, `video_bitrate`, `audio_codec`, `audio_bitrate`, `audio_channels`, `audio_sample_rate`, `audio_resolution`, `width`, `height`, `frame_rate`, `gop_size`, `two_pass`, `conversion_engines`, `conversion_engines_extra_params`, `custom_data`, `view_order`, `bypass_by_extension`, `creation_mode`)
values(12,'0','0','HD (H264)','web,mbr','','2',now(),now(),NULL,'1','mp4','h264','4000','aac','192','0','0','0','0','1080','0','0','0','2','',NULL,'0',NULL,'1');

