
<div id="kmcHeader" >
	<div id="logo"></div>
	<?php if (Infra_AuthHelper::getAuthInstance()->hasIdentity()): ?>
		<?php echo $this->navigation()->menu()->renderMenu(null, array('maxDepth' => 0)); ?>
	<?php endif; ?>
	<h1 class="navigation" > <a class="navigation">Kaltura Applications Hosted Pages</a></h1>
	<div id="user_links">
		<?php if (Infra_AuthHelper::getAuthInstance()->hasIdentity()): ?>
			<span>Hi <?php echo Infra_AuthHelper::getAuthInstance()->getIdentity()->getUser()->firstName; ?></span><br />
			<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), null, true); ?>">Logout</a>
		<?php endif; ?>
	</div>
</div>
