<fieldset id="<?php echo $this->element->getElementsBelongTo(); ?>">
	<?php foreach ($this->element->getElements() as $name => $elem) {
		if (strpos($name,'Dictionary_') > -1)
			echo $elem;
	} ?>

	<input type="hidden" name="belongs" value="<?php echo $this->element->getElementsBelongTo(); ?>" />
	<a class="remove-dictionary" href="javascript:;" onclick="removeDictionary(this);">Remove</a>


</fieldset>