<fieldset id="<?php echo $this->element->getElementsBelongTo(); ?>">
	<?php foreach ($this->element->getElements() as $name => $elem) {
		if (strpos($name,'Rule_') > -1)
			echo $elem;
	} ?>
	
	<input type="hidden" name="belongs" value="<?php echo $this->element->getElementsBelongTo(); ?>" />
	<a class="remove-reachProfileRule" href="javascript:;" onclick="removeRule(this);">Remove</a>


</fieldset>


