<dd id="test">
<fieldset id="vendorProfileRule-fieldSet" class="vendorProfileRule">
	<a class="add-rule" href="javascript:;" style="display:block;" onclick="addRule(this);" >+  Add Rule</a>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<style type="text/css">
		#frmVendorProfileConfigure .vendorProfileRule{ display:block; padding: 10px; min-width: 500px; }
		#frmVendorProfileConfigure .vendorProfileRule span.rule { font-size: 14px; font-weight: bold; }
		#frmVendorProfileConfigure .vendorProfileRule label { padding: 4px 0; }
		#frmVendorProfileConfigure .vendorProfileRule fieldset { min-width: 0; height: auto; margin: 10px 0; padding: 5px; border: 1px solid #CCCCCC; }
		#frmVendorProfileConfigure .vendorProfileRule .remove-vendorProfileRule { padding: 5px; float: right; }
	</style>
</fieldset>
</dd>


<script type="text/javascript">

	var ruleIndex = 0;
	var maxRuleIndex = 0;
	
	function addRule(target)
	{
		var chooseElem = document.getElementById("ruleType");
		var showType = chooseElem.options[chooseElem.selectedIndex].text;
		if (showType == 'None')
			return alert("Please choose vendor profile rule");

		if (jQuery('#rule-fieldSet').attr('disabled'))
			return;

		jQuery('#rule-fieldSet').attr('maxRuleIndex', maxRuleIndex++);
		var ruleTag = 'Rule_' + ruleIndex++;

		var newRule = createRule(ruleTag, showType);

		jQuery(target).before(newRule.show());
	}

	function removeRule(target) {
		if (!jQuery('#rule-fieldSet').attr('disabled')) {
			ruleIndex--;
			$(target).parent().remove();
		}
	}

	function createRule(ruleTag, type) {
		var ruleTemplate = jQuery('#vendorProfileRuleTemplate_' + type);
		ruleTemplate.attr("name", "Template");

		var newData = ruleTemplate.clone(true);
		newData.attr("id", ruleTag).attr("name", ruleTag);
		newData.find("input[id=Rule_ruleType]").val(type);
		newData.find("input,select").each(function (idx) {
			var name = $(this).attr("name");
			var paramName = name.substring("Rule_".length);
			var tag = ruleTag + "::" + paramName;
			if (paramName == "ruleType")
				$(this).attr("readonly","1");
			$(this).attr("name", paramName).attr("id", tag)
		});

		return newData;

	}

	function addRuleFromObject(target, object)
    {
        jQuery('#rule-fieldSet').attr('maxRuleIndex', maxRuleIndex++);
		var ruleTag = 'Rule_' + ruleIndex++;
		var newRule = createRule(ruleTag, object.ruleType);

		newRule.find( "input,select").each(function(idx) {
			if ($( this ).attr("type") == 'hidden')
				return;
			var name = $( this ).attr("name");
			var val = object[name];
			$(this).val(val).attr('checked', val);
		});

		jQuery(target).before(newRule.show());
	}

</script>