<dd id="test">
<fieldset id="source-language-fieldSet" class="source-language">
	<a class="add-source-language" href="javascript:;" onclick="addSourceLanguage(this);" >+ Add Source Language</a>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<style type="text/css">
		#frmCatalogItemConfigure .source-language{ display:block; padding: 10px; min-width: 500px; }
		#frmCatalogItemConfigure .source-language span.rule { font-size: 14px; font-weight: bold; }
		#frmCatalogItemConfigure .source-language label { padding: 4px 0; }
		#frmCatalogItemConfigure .source-language fieldset { min-width: 0; height: auto; margin: 10px 0; padding: 5px; border: 1px solid #CCCCCC; }
		#frmCatalogItemConfigure .source-language .remove-source-language { padding: 5px; float: right; }
		#frmCatalogItemConfigure .source-language dd { display: inline; }
		#frmCatalogItemConfigure .source-language dt { display: inline; }
	</style>
</fieldset>
</dd>


<script type="text/javascript">

	var sourceLanguageIndex = 0;
	var maxSourceLanguageIndex = 0;
	
	function addSourceLanguage(target)
	{
		if (jQuery('#source-language-fieldSet').attr('disabled'))
			return;

        jQuery('#source-language-fieldSet').attr('maxSourceLanguageIndex', maxSourceLanguageIndex++);
		var sourceLanguageTag = 'SourceLanguage_' + sourceLanguageIndex++;
		var newSourceLanguage = createSourceLanguage(sourceLanguageTag);
		
		jQuery(target).after(newSourceLanguage.show());
	}

	function removeSourceLanguage(target) {
		if (!jQuery('#source-language-fieldSet').attr('disabled')) {
			sourceLanguageIndex--;
			$(target).parent().remove();
		}
	}

	function createSourceLanguage(sourceLanguageTag)
	{
		var sourceLanguageTemplate = jQuery('#SourceLanguageTemplate');
        sourceLanguageTemplate.attr("name", "Template");

		var newData = sourceLanguageTemplate.clone(true);
		newData.attr("id", sourceLanguageTag).attr("name", sourceLanguageTag);

		newData.find( "input,select").each(function(idx) {
			var name = $( this ).attr("name");
			var paramName =name.substring("SourceLanguage_".length);
			var tag = sourceLanguageTag + "::" + paramName;
			$( this ).attr("name", paramName).attr("id", tag)
		});

		return newData;
	}

	function addSourceLanguageFromObject(target, object) 
    {
        jQuery('#source-language-fieldSet').attr('maxSourceLanguageIndex', maxSourceLanguageIndex++);
		var sourceLanguageTag = 'SourceLanguage_' + sourceLanguageIndex++;
		var newSourceLanguage = createSourceLanguage(sourceLanguageTag);

		newSourceLanguage.find( "input,select").each(function(idx) {
			if ($( this ).attr("type") == 'hidden')
				return;
			var name = $( this ).attr("name");
			var val = object[name];
			$(this).val(val).attr('checked', val);
		});

		jQuery(target).after(newSourceLanguage.show());
	}


</script>



