<fieldset class="source-language">
	<legend>SourceLanguage:</legend>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<a class="add-source-langeuage" href="javascript:;" onclick="addSourceLanguage(this);" >+ Add Source Language</a>
</fieldset>

<style type="text/css">
	#frmCatalogItemConfigure .source-language{ display: block; padding: 10px; }
	#frmCatalogItemConfigure .source-language span.rule { font-size: 14px; font-weight: bold; }
	#frmCatalogItemConfigure .source-language label { display: block; padding: 4px 0; }
	#frmCatalogItemConfigure .source-language fieldset { min-width: 0; height: auto; margin: 6px 0; padding: 10px; border: 1px solid #CCCCCC; }
	#frmCatalogItemConfigure .source-language .remove-source-language { float: right; }
</style>

<script type="text/javascript">

	var condIndex = 0;
	function addSourceLanguage(target)
	{
		var sourceLanguageTag = 'SourceLanguage_' + condIndex++;
		var newSourceLanguage = createSourceLanguage(sourceLanguageTag);
		jQuery(target).before(newSourceLanguage.show());
	}

	function removeSourceLanguage(target) {
		condIndex--;
		jQuery(target).parent().remove();
	}

	function createSourceLanguage(taskTag)
	{
		var condTemplate = jQuery('#SourceLanguageTemplate' );
		condTemplate.attr("name", "Template");

		var newData = condTemplate.clone(true);
		newData.attr("id", taskTag).attr("name", taskTag);

		newData.find( "input,select").each(function(idx) {
			var name = $( this ).attr("name");
			var paramName =name.substring("SourceLanguage_".length);
			var tag = taskTag + "::" + paramName;
			$( this ).attr("name", paramName).attr("id", tag)
		});

		return newData;
	}



	function addSourceLanguageFromObject(target, object) {
		var condTag = 'SourceLanguage_' + condIndex++;
		var newSourceLanguage = createSourceLanguage(condTag);

//		newSourceLanguage.find( "input,select").each(function(idx) {
//			if ($( this ).attr("type") == 'hidden')
//				return;
//			var name = $( this ).attr("name");
//			var val = object[name];
//			$(this).val(val).attr('checked', val);
//		});

		jQuery(target).before(newSourceLanguage.show());
	}


</script>



