<dd id="test">
<fieldset class="target-language">
	<legend>TargetLanguage:</legend>
	<a class="add-target-language" href="javascript:;" onclick="addTargetLanguage(this);" >+ Add Target Language</a>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<style type="text/css">
		#frmCatalogItemConfigure .target-language{ display:block; padding: 10px; min-width: 500px; }
		#frmCatalogItemConfigure .target-language span.rule { font-size: 14px; font-weight: bold; }
		#frmCatalogItemConfigure .target-language label { padding: 4px 0; }
		#frmCatalogItemConfigure .target-language fieldset { min-width: 0; height: auto; margin: 10px 0; padding: 5px; border: 1px solid #CCCCCC; }
		#frmCatalogItemConfigure .target-language .remove-target-language { padding: 5px; float: right; }
		#frmCatalogItemConfigure .target-language dd { display: inline; }
		#frmCatalogItemConfigure .target-language dt { display: inline; }
	</style>
</fieldset>
</dd>


<script type="text/javascript">

	var targetLanguageIndex = 0;
	function addTargetLanguage(target)
	{
		var targetLanguageTag = 'TargetLanguage_' + targetLanguageIndex++;
		var newTargetLanguage = createTargetLanguage(targetLanguageTag);
		
		jQuery(target).after(newTargetLanguage.show());
	}

	function removeTargetLanguage(target) {
        targetLanguageIndex--;
		jQuery(target).parent().remove();
	}

	function createTargetLanguage(targetLanguageTag)
	{
		var targetLanguageTemplate = jQuery('#TargetLanguageTemplate');
        targetLanguageTemplate.attr("name", "Template");

		var newData = targetLanguageTemplate.clone(true);
		newData.attr("id", targetLanguageTag).attr("name", targetLanguageTag);

		newData.find( "input,select").each(function(idx) {
			var name = $( this ).attr("name");
			var paramName =name.substring("TargetLanguage_".length);
			var tag = taskTag + "::" + paramName;
			$( this ).attr("name", paramName).attr("id", tag)
		});

		return newData;
	}

	function addTargetLanguageFromObject(target, object) {
		var targetLanguageTag = 'TargetLanguage_' + targetLanguageIndex++;
		var newTargetLanguage = createTargetLanguage(targetLanguageTag);

		newTargetLanguage.find( "input,select").each(function(idx) {
			if ($( this ).attr("type") == 'hidden')
				return;
			var name = $( this ).attr("name");
			var val = object[name];
			$(this).val(val).attr('checked', val);
		});

		jQuery(target).after(newTargetLanguage.show());
	}

</script>



