<?php
/**
 * @package plugins.huluDistribution
 * @subpackage model.enum
 */ 
interface HuluDistributionField extends BaseEnum
{
	const SERIES_TITLE = 'SERIES_TITLE';
	const SERIES_DESCRIPTION = 'SERIES_DESCRIPTION';
	const SERIES_PRIMARY_CATEGORY = 'SERIES_PRIMARY_CATEGORY';
	const SERIES_ADDITIONAL_CATEGORIES = 'SERIES_ADDITIONAL_CATEGORIES';
	const SERIES_CHANNEL = 'SERIES_CHANNEL';
	const SEASON_NUMBER = 'SEASON_NUMBER';
	const SEASON_SYNOPSIS = 'SEASON_SYNOPSIS';
	const SEASON_TUNEIN_INFORMATION = 'SEASON_TUNEIN_INFORMATION';
	const VIDEO_MEDIA_TYPE = 'VIDEO_MEDIA_TYPE';
	const VIDEO_TITLE = 'VIDEO_TITLE';
	const VIDEO_EPISODE_NUMBER = 'VIDEO_EPISODE_NUMBER';
	const VIDEO_RATING = 'VIDEO_RATING';
	const VIDEO_CONTENT_RATING_REASON = 'VIDEO_CONTENT_RATING_REASON';
	const VIDEO_AVAILABLE_DATE = 'VIDEO_AVAILABLE_DATE';
	const VIDEO_EXPIRATION_DATE = 'VIDEO_EXPIRATION_DATE';
	const VIDEO_DESCRIPTION = 'VIDEO_DESCRIPTION';
	const VIDEO_FULL_DESCRIPTION = 'VIDEO_FULL_DESCRIPTION';
	const VIDEO_COPYRIGHT = 'VIDEO_COPYRIGHT';
	const VIDEO_KEYWORDS = 'VIDEO_KEYWORDS';
	const VIDEO_LANGUAGE = 'VIDEO_LANGUAGE';
	const VIDEO_PROGRAMMING_TYPE = 'VIDEO_PROGRAMMING_TYPE';
	const VIDEO_EXTERNAL_ID = 'VIDEO_EXTERNAL_ID';
	const VIDEO_ORIGINAL_PREMIERE_DATE = 'VIDEO_ORIGINAL_PREMIERE_DATE';
	const VIDEO_SEGMENTS = 'VIDEO_SEGMENTS';
}