<?php if($this->element->getValue()) : ?>
	<fieldset>
		<legend>Authorize API Access</legend>
		<div>
			<input type="text" value="<?php echo $this->element->getValue(); ?>" id="api_authorize_url" style="width:310px; margin: 10px 0"/>
			<p>Link to get the needed token to publish on given pageId, send this link to the person who has access to the KMC and the Facebook account.</p>
			<p>Requires two steps login:<br/>1. KMC credentials <br/>2. Facebook credentials.</p>
		</div>
	</fieldset>
<?php endif; ?>