<?php if($this->element->getValue()) : ?>
<fieldset>
	<dt>
		<label>Authorize API Access</label>
	</dt>
	<dd>
		<input type="text" value="<?php echo $this->element->getValue(); ?>" id="api_authorize_url">
		<p class="description">Link to get the needed token to publish on given pageId, send this link to the person who has access to the KMC and the Facebook account.</p>
		<p class="description">Requires two steps login:<br/>1. KMC credentials <br/>2. Facebook credentials.</p>
	</dd>
</fieldset>
<?php endif; ?>