<?php if (!$this->kavaDashboardUrl) {echo $this->translate('Missing setting to generate kava dashboard url'); return;} ?>
<style type="text/css">
        #sub-header { padding: 5px 20px 0px; }
        #wrapper { padding: 0 0 0 0; width: 100%; }

</style>
<iframe id="kavaIframe" width="100%" height="100%" src="about:blank" frameborder="0" class="auto-height"></iframe>
<script type="text/javascript">
    var url = window.location;
    var urlBase = url.origin + url.pathname;
    document.getElementById('kavaIframe').src = '<?php echo($this->kavaDashboardUrl)?>&baseUrl=' + encodeURIComponent(urlBase) + window.location.hash;
</script>
