<?php if (!$this->kelloggsUrl) {echo $this->translate('Missing setting to generate kelloggs dashboard url'); return;} ?>
<style type="text/css">
        #sub-header { padding: 5px 20px 0px; }
        #wrapper { padding: 0 0 0 0; width: 100%; }
</style>
<iframe id="kelloggsIframe" width="100%" height="100%" src="about:blank" frameborder="0" class="auto-height"></iframe>
<script type="text/javascript">
  var initialized = false;
  (function(window) {

    if (initialized) {
      return;
    }

    initialized = true;

    var url = window.location;
    var hostUrl = url.origin + url.pathname;

    var appConfig = {
      'type': 'config',
      'config': {
        'hostUrl': hostUrl,
        'serviceUrl': '<?php echo $this->kelloggsServiceUrl; ?>',
        'jwt': '<?php echo $this->kelloggsJwt; ?>',
      }
    };

    if (!appConfig.config.jwt || !appConfig.config.serviceUrl) {
      alert("Cannot initialize test page, missing configuration. Please modify file index.html to include jwt and service url");
      return;
    }

    window.document.getElementById('kelloggsIframe').src = '<?php echo $this->kelloggsUrl; ?>' + url.hash;

    window.addEventListener('message', function(e) {
      var postMessageData;
      try {
        postMessageData = e.data;
      }
      catch(ex) {
        return;
      }

      if(postMessageData.type === 'request-config') {
        e.source.postMessage(appConfig, e.origin);
      }
    });
  })(window);
</script>
