<?php
interface PermissionName extends BaseEnum
{
	// special services
	
	const FEATURE_ANALYTICS_TAB = 'FEATURE_ANALYTICS_TAB';
	const FEATURE_508_PLAYERS = 'FEATURE_508_PLAYERS';
	const FEATURE_LIVE_STREAM = 'FEATURE_LIVE_STREAM';
	const FEATURE_VAST = 'FEATURE_VAST';
	const FEATURE_SILVERLIGHT = 'FEATURE_SILVERLIGHT';
	
	
	// base system permissions
	
	const USER_SESSION_PERMISSION = 'BASE_USER_SESSION_PERMISSION';
	const NO_SESSION_PERMISSION = 'NO_SESSION_PERMISSION';
	
	// batch related permissions
	
	const BASE_BATCH_SYSTEM_PERMISSION = 'BASE_BATCH_SYSTEM_PERMISSION';
	
	// user actions permissions
	
	const CONTENT_INGEST_UPLOAD = 'CONTENT_INGEST_UPLOAD';
	const CONTENT_INGEST_BULK_UPLOAD = 'CONTENT_INGEST_BULK_UPLOAD';
	const CONTENT_INGEST_FEED = 'CONTENT_INGEST_FEED';
	
	const CONTENT_MANAGE_MIX = 'CONTENT_MANAGE_MIX';
	const CONTENT_MANAGE_BASE = 'CONTENT_MANAGE_BASE';
	const CONTENT_MANAGE_METADATA = 'CONTENT_MANAGE_METADATA';
	const CONTENT_MANAGE_ASSIGN_CATEGORIES = 'CONTENT_MANAGE_ASSIGN_CATEGORIES';
	const CONTENT_MANAGE_THUMBNAIL = 'CONTENT_MANAGE_THUMBNAIL';
	const CONTENT_MANAGE_SCHEDULE = 'CONTENT_MANAGE_SCHEDULE';
	const CONTENT_MANAGE_ACCESS_CONTROL = 'CONTENT_MANAGE_ACCESS_CONTROL';
	const CONTENT_MANAGE_CUSTOM_DATA = 'CONTENT_MANAGE_CUSTOM_DATA';
	const CONTENT_MANAGE_DELETE = 'CONTENT_MANAGE_DELETE';
	const CONTENT_MANAGE_RECONVERT = 'CONTENT_MANAGE_RECONVERT';
	const CONTENT_MANAGE_EDIT_CATEGORIES = 'CONTENT_MANAGE_EDIT_CATEGORIES';
	const CONTENT_MANAGE_ANNOTATION = 'CONTENT_MANAGE_ANNOTATION';
	const CONTENT_MANAGE_SHARE = 'CONTENT_MANAGE_SHARE';
	
	const LIVE_STREAM_BASE = 'LIVE_STREAM_BASE';
	const LIVE_STREAM_ADD = 'LIVE_STREAM_ADD';
	const LIVE_STREAM_UPDATE = 'LIVE_STREAM_UPDATE';
		
	const CONTENT_MODERATE_BASE = 'CONTENT_MODERATE_BASE';
	const CONTENT_MODERATE_METADATA = 'CONTENT_MODERATE_METADATA';
	const CONTENT_MODERATE_CUSTOM_DATA = 'CONTENT_MODERATE_CUSTOM_DATA';
	
	const PLAYLIST_BASE = 'PLAYLIST_BASE';
	const PLAYLIST_ADD = 'PLAYLIST_ADD';
	const PLAYLIST_UPDATE = 'PLAYLIST_UPDATE';
	const PLAYLIST_DELETE = 'PLAYLIST_DELETE';
	
	const SYNDICATION_BASE = 'SYNDICATION_BASE';
	const SYNDICATION_ADD = 'SYNDICATION_ADD';
	const SYNDICATION_UPDATE = 'SYNDICATION_UPDATE';
	const SYNDICATION_DELETE = 'SYNDICATION_DELETE';
	
	const STUDIO_BASE = 'STUDIO_BASE';
	const STUDIO_ADD_UICONF = 'STUDIO_ADD_UICONF';
	const STUDIO_UPDATE_UICONF = 'STUDIO_UPDATE_UICONF';
	const STUDIO_DELETE_UICONF = 'STUDIO_DELETE_UICONF';

	const ACCOUNT_BASE = 'ACCOUNT_BASE';
	const ACCOUNT_UPDATE_SETTINGS = 'ACCOUNT_UPDATE_SETTINGS';
	
	const INTEGRATION_BASE = 'INTEGRATION_BASE';
	const INTEGRATION_UPDATE_SETTINGS = 'INTEGRATION_UPDATE_SETTINGS';
	
	const ACCESS_CONTROL_BASE = 'ACCESS_CONTROL_BASE';
	const ACCESS_CONTROL_ADD = 'ACCESS_CONTROL_ADD';
	const ACCESS_CONTROL_UPDATE = 'ACCESS_CONTROL_UPDATE';
	const ACCESS_CONTROL_DELETE = 'ACCESS_CONTROL_DELETE';
	
	const TRANSCODING_BASE = 'TRANSCODING_BASE';
	const TRANSCODING_ADD = 'TRANSCODING_ADD';
	const TRANSCODING_UPDATE = 'TRANSCODING_UPDATE';
	const TRANSCODING_DELETE = 'TRANSCODING_DELETE';
	
	const CUSTOM_DATA_PROFILE_BASE = 'CUSTOM_DATA_PROFILE_BASE';
	const CUSTOM_DATA_PROFILE_ADD = 'CUSTOM_DATA_PROFILE_ADD';
	const CUSTOM_DATA_PROFILE_UPDATE = 'CUSTOM_DATA_PROFILE_UPDATE';
	const CUSTOM_DATA_PROFILE_DELETE = 'CUSTOM_DATA_PROFILE_DELETE';
	
	const ADMIN_BASE = 'ADMIN_BASE';
	const ADMIN_USER_ADD = 'ADMIN_USER_ADD';
	const ADMIN_USER_UPDATE = 'ADMIN_USER_UPDATE';
	const ADMIN_USER_DELETE = 'ADMIN_USER_DELETE';
	
	const ADMIN_ROLE_ADD = 'ADMIN_ROLE_ADD';
	const ADMIN_ROLE_UPDATE = 'ADMIN_ROLE_UPDATE';
	const ADMIN_ROLE_DELETE = 'ADMIN_ROLE_DELETE';
	
	const ADMIN_PUBLISHER_MANAGE = 'ADMIN_PUBLISHER_MANAGE';
	const ANALYTICS_BASE = 'ANALYTICS_BASE';
	
	
	// KMC only permissions
	
	const ADVERTISING_BASE = 'ADVERTISING_BASE';
	const ADVERTISING_UPDATE_SETTINGS = 'ADVERTISING_UPDATE_SETTINGS';
	const PLAYLIST_EMBED_CODE = 'PLAYLIST_EMBED_CODE';
	const STUDIO_BRAND_UICONF = 'STUDIO_BRAND_UICONF';
	const STUDIO_SELECT_CONTENT = 'STUDIO_SELECT_CONTENT';
	const CONTENT_MANAGE_EMBED_CODE = 'CONTENT_MANAGE_EMBED_CODE';

	
	// not valid yet
	
	const ADMIN_WHITE_BRANDING = 'ADMIN_WHITE_BRANDING';		
}
