<div id="addItemXpath">
	<a href="#" class="add-item-xpath">+ Add </a>
</div>

<script type="text/javascript">
    $(function() {
        $('#fieldset-itemXpathsToExtend_group input').attr('name', 'itemXpathsToExtend[]');

        $('a.add-item-xpath').click(function() {
            $new = $('#fieldset-itemXpathsToExtend_group input:first').parent().clone();
            $new.find('input').val('');
            $(this).parent().before($new);
            return false;
        });

    });
</script>

<style>
	#fieldset-itemXpathsToExtend_group div { margin: 10px 0; }
	#fieldset-itemXpathsToExtend_group input { width: 100%; }
</style>