
<p><?php echo $this->translate('partner-usage intro text'); ?></p>
<ul>
 <li><?php echo $this->translate('partner-usage intro text2'); ?></li>
 <li><?php echo $this->translate('partner-usage intro text3'); ?></li>
</ul>
<?php echo $this->form; ?>
<div id="resultsTotal" class="clear">
	<h2>Total<?php $this->paginator->getItemsCount(); ?></h2>
	<table class="clear">
		<thead>
			<tr>
				<th title="<?php echo $this->translate('partner-usage table bandwidth tooltip'); ?>"><?php echo $this->translate('partner-usage table bandwidth'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table storage tooltip'); ?>"><?php echo $this->translate('partner-usage table storage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table peakStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table peakStorage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table averageStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table averageStorage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table combinedBandwidthStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table combinedBandwidthStorage'); ?></th>
			</tr>
		</thead>
		<tbody>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><?php echo Zend_Locale_Format::toNumber((int)$this->paginator->getTotal()->bandwidth); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$this->paginator->getTotal()->storage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$this->paginator->getTotal()->peakStorage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$this->paginator->getTotal()->avgStorage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$this->paginator->getTotal()->combinedStorageBandwidth); ?> MB</td>
			</tr>
		</tbody>
	</table>
</div>
<div id="resultsSubs" class="clear">
	<h2>Details <span>(<?php echo $this->paginator->getItemsCount(); ?> results | <a class="exportCsv"><?php echo $this->translate('Export to CSV'); ?></a>)</span></h2>
	<table class="clear">
		<thead>
			<tr>
				<th title="<?php echo $this->translate('partner-usage table timeUnit tooltip'); ?>"><?php echo $this->translate('partner-usage table timeUnit'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table partnerStatus tooltip'); ?>"><?php echo $this->translate('partner-usage table partnerStatus'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table partnerName tooltip'); ?>"><?php echo $this->translate('partner-usage table partnerName'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table partnerId tooltip'); ?>"><?php echo $this->translate('partner-usage table partnerId'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table partnerCreatedAt tooltip'); ?>"><?php echo $this->translate('partner-usage table partnerCreatedAt'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table bandwidth tooltip'); ?>"><?php echo $this->translate('partner-usage table bandwidth'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table storage tooltip'); ?>"><?php echo $this->translate('partner-usage table storage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table peakStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table peakStorage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table averageStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table averageStorage'); ?></th>
				<th title="<?php echo $this->translate('partner-usage table combinedBandwidthStorage tooltip'); ?>"><?php echo $this->translate('partner-usage table combinedBandwidthStorage'); ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="16"><?php echo $this->paginator; ?></td>
			</tr>
		</tfoot>
		<tbody>
			<?php foreach($this->paginator as $item): ?>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><?php $d = strlen($item->dateId) == 6 ? DateTime::createFromFormat("Ym", $item->dateId) : DateTime::createFromFormat("Ymd", $item->dateId); echo strlen($item->dateId) == 6 ? $d->format("M Y") : $d->format("d M Y"); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Enum_PartnerStatus', $item->partnerStatus); ?></td>
				<td><?php echo $item->partnerName; ?></td>
				<td><?php echo $item->partnerId; ?></td>
				<td><?php $d = (new Zend_Date($item->partnerCreatedAt)); echo $d->toString(Zend_Date::DATE_LONG); ?></td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$item->bandwidth); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$item->storage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$item->peakStorage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$item->avgStorage); ?> MB</td>
				<td><?php echo Zend_Locale_Format::toNumber((int)$item->combinedStorageBandwidth); ?> MB</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<a class="exportCsv"><?php echo $this->translate('Export to CSV'); ?></a>
</div>

<script type="text/javascript">
jQuery('#filter_type').change(function() {
	if(this.value == "none") {
		$("#filter_text").css("display","none");
		$("div.help").hide();
	}
	else {
		$("#filter_text").css("display","inline");
		$("#filter_text input").focus();
		if(this.value == "free")
			$("div.help").show();
		else
			$("div.help").hide();
	}
});

jQuery('#filter_type').change();

jQuery('#clear_dates').click(function() {
	jQuery('#from_date').val('');
	jQuery('#to_date').val('');
});

jQuery('#from_date').change( function() {
	jQuery('#date_range').val('custom');
});

jQuery('#to_date').change( function() {
	jQuery('#date_range').val('custom');
});


jQuery('#date_range').change(function() {
	var from;
	var to;
	switch (this.value)
	{
		case "yesterday":
			from = new Date();
			from.setDate(from.getDate() - 1);
			to = new Date();
			to.setDate(to.getDate() - 1);
			break;
		case "last_7_days":
			from = new Date();
			to = new Date();
			from.setDate(from.getDate() - 8);
			to.setDate(to.getDate()-2);
			break;
		case "week":
			from = new Date();
			to = new Date();
			from.setDate(from.getDate() - 7);
			to.setDate(to.getDate()-2);
			break;
		case "last_week":
			break;
		case "last_30_days":
			from = new Date();
			to = new Date();
			from.setDate(from.getDate() - 30);
			to.setDate(to.getDate()-2);
			break;
		case "this_month":
			from = new Date();
			to = new Date();
			from.setDate(1);
			to.setDate(to.getDate()-2);
			break;
		case "last_month":
			from = new Date();
			to = new Date();
			from.setMonth(from.getMonth()-1, 1);
			to.setMonth(to.getMonth(), 0);
			break;
		case "last_12_months":
			from = new Date();
			to = new Date();
			from.setMonth(to.getMonth()-12);
			to.setDate(to.getDate()-2);
			break;
		case "this_year":
			from = new Date();
			to = new Date();
			from.setFullYear(to.getFullYear(), 0, 1);
			to.setDate(to.getDate()-2);
			break;
		case "custom":
			//do nothing
			break;
	}

	jQuery('#from_date').val(formatDate(from));
	jQuery('#to_date').val(formatDate(to));
});


function formatDate(date) {
	var dd = date.getDate();
	var mm = date.getMonth()+1;//January is 0!
	var yyyy = date.getFullYear();
	if(dd<10) {
		dd='0'+dd;
	}
	if(mm<10) {
		mm='0'+mm;
	}

	return mm+'/'+dd+'/'+yyyy ;
}

jQuery('.exportCsv').click(function() {
	// change the form action to the csv handler
	jQuery('form:first')
		.attr('action', '<?php echo $this->url(array('controller' => 'partner-usage', 'action' => 'export-csv')); ?>')
		.attr('target', '_blank')
		.find('#do_filter')
		.click();
	
	// restore
	jQuery('form:first')
		.attr('action', null)
		.attr('target', null);
});

jQuery(function(){
	jQuery('#from_date, #to_date').datepicker({showOn: 'both', buttonImage: '<?php echo $this->baseUrl('images/calendar.gif'); ?>', buttonImageOnly: true});
});

</script>
