ALTER TABLE kvote MODIFY kshow_id VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE kshow_kuser MODIFY kshow_id VARCHAR(20);
ALTER TABLE batch_job MODIFY entry_id VARCHAR(20);
ALTER TABLE conversion MODIFY entry_id VARCHAR(20);
ALTER TABLE puser_role MODIFY kshow_id VARCHAR(20);
ALTER TABLE widget_log MODIFY kshow_id VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE notification MODIFY object_id VARCHAR(20);
ALTER TABLE moderation MODIFY object_id VARCHAR(20);
ALTER TABLE moderation_flag MODIFY flagged_entry_id VARCHAR(20);
ALTER TABLE kwidget_log MODIFY kshow_id  VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE widget_log MODIFY kshow_id  VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE widget MODIFY kshow_id VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE roughcut_entry MODIFY roughcut_id VARCHAR(20), MODIFY roughcut_kshow_id VARCHAR(20), MODIFY entry_id VARCHAR(20);
ALTER TABLE kshow MODIFY id VARCHAR(20), MODIFY episode_id VARCHAR(20), MODIFY show_entry_id VARCHAR(20);
ALTER TABLE entry MODIFY id VARCHAR(20), MODIFY kshow_id VARCHAR(20);
ALTER TABLE collect_stats MODIFY entry_id VARCHAR(20), MODIFY widget_id VARCHAR(32);