<?php
/**
 * @package plugins.youTubeDistribution
 * @subpackage model.enum
 */ 
interface YouTubeDistributionField extends BaseEnum
{
	// item
	const NOTIFICATION_EMAIL 			= 'NOTIFICATION_EMAIL';
	const OWNER_NAME 					= 'OWNER_NAME';
	const TARGET 						= 'TARGET';
	const DATE_RECORDED 				= 'DATE_RECORDED';
	const LANGUAGE  					= 'LANGUAGE';
	const START_TIME  					= 'START_TIME';
	const END_TIME  					= 'END_TIME';
	const URGENT_REFERENCE_FILE			= 'URGENT_REFERENCE_FILE';
	const KEEP_FINGERPRINT				= 'KEEP_FINGERPRINT';
	
	// item/yt:account
	const ACCOUNT_USERNAME 				= 'ACCOUNT_USERNAME';
	const ACCOUNT_PASSWORD 				= 'ACCOUNT_PASSWORD';
	
	// item/media:content
	const MEDIA_TITLE  					= 'MEDIA_TITLE';
	const MEDIA_DESCRIPTION  			= 'MEDIA_DESCRIPTION';
	const MEDIA_KEYWORDS  				= 'MEDIA_KEYWORDS';
	const MEDIA_CATEGORY  				= 'MEDIA_CATEGORY';
	const MEDIA_RATING  				= 'MEDIA_RATING';
	
	// item/yt:community
	const ALLOW_COMMENTS  				= 'ALLOW_COMMENTS';
	const ALLOW_RESPONSES  				= 'ALLOW_RESPONSES';
	const ALLOW_RATINGS  				= 'ALLOW_RATINGS';
	const ALLOW_EMBEDDING  				= 'ALLOW_EMBEDDING';
	
	// item/yt:policy
	const POLICY_COMMERCIAL  			= 'POLICY_COMMERCIAL';
	const POLICY_UGC 					= 'POLICY_UGC';

	// item/yt:web_metadata
	const WEB_METADATA_CUSTOM_ID  		= 'WEB_METADATA_CUSTOM_ID';
	const WEB_METADATA_NOTES  			= 'WEB_METADATA_NOTES';
	
	// item/yt:movie_metadata
	const MOVIE_METADATA_CUSTOM_ID 		= 'MOVIE_METADATA_CUSTOM_ID';
	const MOVIE_METADATA_DIRECTOR 		= 'MOVIE_METADATA_DIRECTOR';
	const MOVIE_METADATA_NOTES  		= 'MOVIE_METADATA_NOTES';
	const MOVIE_METADATA_TITLE 			= 'MOVIE_METADATA_TITLE';
	const MOVIE_METADATA_TMS_ID 		= 'MOVIE_METADATA_TMS_ID';
	
	// item/yt:tv_metadata
	const TV_METADATA_CUSTOM_ID  		= 'TV_METADATA_CUSTOM_ID';
	const TV_METADATA_SHOW_TITLE 		= 'TV_METADATA_SHOW_TITLE';
	const TV_METADATA_EPISODE 			= 'TV_METADATA_EPISODE';
	const TV_METADATA_EPISODE_TITLE 	= 'TV_METADATA_EPISODE_TITLE';
	const TV_METADATA_NOTES 			= 'TV_METADATA_NOTES';
	const TV_METADATA_SEASON 			= 'TV_METADATA_SEASON';
	const TV_METADATA_TMS_ID 			= 'TV_METADATA_TMS_ID';
	
	// item/yt:playlists
	const PLAYLISTS 					= 'PLAYLISTS';

	// item/yt:advertising
	const ADVERTISING_ADSENSE_FOR_VIDEO = 'ADVERTISING_ADSENSE_FOR_VIDEO';
	const ADVERTISING_INVIDEO			= 'ADVERTISING_INVIDEO';
	const ADVERTISING_ALLOW_PRE_ROLL_ADS 	= 'ADVERTISING_ALLOW_PRE_ROLL_ADS';
	const ADVERTISING_ALLOW_POST_ROLL_ADS 	= 'ADVERTISING_ALLOW_POST_ROLL_ADS';
	
	// item/yt:advertising/yt:third_party_ads
	const THIRD_PARTY_AD_SERVER_AD_TYPE 	= 'THIRD_PARTY_AD_SERVER_AD_TYPE';
	const THIRD_PARTY_AD_SERVER_PARTNER_ID 	= 'THIRD_PARTY_AD_SERVER_PARTNER_ID';
	const THIRD_PARTY_AD_SERVER_VIDEO_ID 	= 'THIRD_PARTY_AD_SERVER_VIDEO_ID';
	
	// item/yt:location
	const LOCATION_COUNTRY 				= 'LOCATION_COUNTRY';
	const LOCATION_LOCATION_TEXT		= 'LOCATION_LOCATION_TEXT';
	const LOCATION_ZIP_CODE				= 'LOCATION_ZIP_CODE';
	
	// item/yt:distribution_restriction
	const DISTRIBUTION_RESTRICTION_DISTRIBUTION_RULE = 'DISTRIBUTION_RESTRICTION_DISTRIBUTION_RULE';
	
}