
<script type="text/javascript">


jQuery(document).ready(function() {
	jQuery('#server_id').change(function(){
		var select = jQuery('#process_id');

		select.empty();
		select.append('<option value="">Select Process</option>');

		var partnerId = jQuery('#newPartnerId').val();
		var serverId = jQuery('#server_id').val();
		
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'BusinessProcessNotificationTemplatesListProcessesAction', 'partner_id' => 'PARTNER_ID', 'server_id' => 'SERVER_ID')); ?>';
		url = url.replace('PARTNER_ID', partnerId);
		url = url.replace('SERVER_ID', serverId);
		jQuery.ajax({
			url: url,
			dataType: 'json',
			success: function(result) {
				if (typeof result === 'object'){
					for(var value in result){
						select.append('<option value="' + value + '">' + result[value] + '</option>');
					}
				}
				else{
					this.error(result);
				}
			},
			error: function(result) {
				alert('<?php echo $this->translate('An error occured'); ?>: ' + result);
			}
		});
	});
});


</script>