default:
  has_layout: on
  layout: systemlayout
  
  stylesheets: 
  javascripts: 
 
defSystemSuccess:
  layout: emptylayout
  stylesheets: 
 
newDashboardSuccess:
  stylesheets: 
  javascripts: 
  
viewShowsSuccess:
  stylesheets: 
  javascripts: 

viewUsersSuccess:
  stylesheets: 
  javascripts: 

viewWidgetsSuccess:
  stylesheets: 
  javascripts: 

viewPartnersSuccess:
  stylesheets: 
  javascripts: 

viewPartnersASuccess:
  stylesheets: 
  javascripts: 

viewUiconfSuccess:
  stylesheets: 
  javascripts: 
  
editUiconfSuccess:
  stylesheets: 
  javascripts: 
  
kcwUiConfEditorSuccess:
  stylesheets: 
  javascripts: 
  
addUiconfSuccess:
  stylesheets: 
  javascripts: 
  
createWidgetsFromUiConfSuccess:
  stylesheets: 
  javascripts: 
  
viewUiconfWidgetsSuccess:
  stylesheets: 
  javascripts: 

showtimeSuccess:
  has_layout: off


editPrNewsSuccess:
  stylesheets: 
  javascripts: 

emailCampaignMgrSuccess:
  stylesheets: 
  javascripts: 

editPartnershipSuccess:
  stylesheets: 
  javascripts: 

uploadSuccess: 
  stylesheets: 
  
conversionProfileSuccess:
  has_layout: on
  layout: emptylayout

conversionParamsSuccess:
  has_layout: on
  layout: emptylayout
  
partnerWidgetStatsSuccess:
  has_layout: off
  
gallerySuccess:
  javascripts:    [  /lib/js/jquery-1.3.1.min.js ]	
  
toolsSuccess:
  javascripts:    [  /lib/js/jquery-1.3.1.min.js ]

investigateSuccess:
  javascripts:    [ /lib/js/jquery.v1.4.2.min.js ]
  
dashSuccess:
  has_layout: off
  
