<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php
	$this->form->setAction($this->url(array('controller' => 'plugin', 'action' => 'DropFolderConfigureAction')));
	echo $this->form;
?>




<script type="text/javascript">

jQuery(document).ready(function() {
	handlerTypeChanged();
});


function handlerTypeChanged()
{
	curValue = jQuery('#frmDropFolderConfigure #fileHandlerType').val();
	if (curValue == <?php echo Kaltura_Client_DropFolder_Enum_DropFolderFileHandlerType::CONTENT; ?>) {
		jQuery('#frmDropFolderConfigure #frmContentFileHandlerConfig').css("display","inline");
	}
	else {
		jQuery('#frmDropFolderConfigure #frmContentFileHandlerConfig').css("display","none");
	}	
}

                                   
jQuery(document).ready(function() {
	<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmPaginator1').submit();
	<?php else: ?>
		jQuery('#frmDropFolderConfigure').ajaxForm(loadDropFolderSuccess);
	<?php endif; ?>
});                                   

</script>

