<?php
/**
 * @package plugins.verizonVcastDistribution
 * @subpackage model.enum
 */ 
interface VerizonVcastDistributionField extends BaseEnum
{
	const TITLE = 'TITLE';
	const EXTERNAL_ID = 'EXTERNAL_ID';
	const ISRC = 'ISRC';
	const UPC = 'UPC';
	const SHORT_DESCRIPTION = 'SHORT_DESCRIPTION';
	const DESCRIPTION = 'DESCRIPTION';
	const KEYWORDS = 'KEYWORDS';
	const PROGRAM_NAME = 'PROGRAM_NAME';
	const PROGRAM_CODE = 'PROGRAM_CODE';
	const PROGRAM_DESCRIPTION = 'PROGRAM_DESCRIPTION';
	const VIDEO_TYPE = 'VIDEO_TYPE';
	const VIDEO_DESCRIPTORS = 'VIDEO_DESCRIPTORS';
	const SEASON = 'SEASON';
	const EPISODE = 'EPISODE';
	const STUDIO = 'STUDIO';
	const ORIGINAL_COUNTRY = 'ORIGINAL_COUNTRY';
	const ORIGINAL_RELEASE = 'ORIGINAL_RELEASE';
	const PUB_DATE = 'PUB_DATE';
	const CATEGORY = 'CATEGORY';
	const CATEGORY_DESCRIPTOR = 'CATEGORY_DESCRIPTOR';
	const SUB_CATEGORY_DESCRIPTOR = 'SUB_CATEGORY_DESCRIPTOR';
	const GENRE = 'GENRE';
	const TOP_STORY = 'TOP_STORY';
	const SORT_NAME = 'SORT_NAME';
	const RATING = 'RATING';
	const RATING_DESCRIPTOR = 'RATING_DESCRIPTOR';
	const COPYRIGHT = 'COPYRIGHT';
	const ENTITLEMENT = 'ENTITLEMENT';
	const LIVE_DATE = 'LIVE_DATE';
	const END_DATE = 'END_DATE';
	const PURCHASE_END_DATE = 'PURCHASE_END_DATE';
	const PRIORITY = 'PRIORITY';
	const ALLOW_STREAMING = 'ALLOW_STREAMING';
	const STREAMING_PRICE_CODE = 'STREAMING_PRICE_CODE';
	const ALLOW_DOWNLOAD = 'ALLOW_DOWNLOAD';
	const DOWNLOAD_PRICE_CODE = 'DOWNLOAD_PRICE_CODE';
	const PROVIDER = 'PROVIDER';
	const PROVIDER_ID = 'PROVIDER_ID';
	const ALERT_CODE = 'ALERT_CODE';

}