
<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php echo $this->form ?>

<script type="text/javascript">

	$('fieldset[id^="SourceLanguageTemplate"]').hide();
	populateConditions("SourceLanguages", "add-source-language");

	$('fieldset[id^="TargetLanguageTemplate"]').hide();
	populateConditions("TargetLanguages", "add-target-language");

	function populateConditions(name, file ) {
		var data = jQuery('#'+name).val();
		if (!data)
			return;
		var arr = JSON.parse(data);
		var ts = $( "." + file );
		for (var i = 0, len = arr.length; i < len; i++)
			if ( name == 'SourceLanguages')
				addSourceLanguageFromObject(ts, arr[i]);
			else
				addTargetLanguageFromObject(ts, arr[i]);
	}

	jQuery(function() {
		<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmCatalogItemConfigure').submit();
		<?php endif; ?>
	});

</script>