
<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php echo $this->form ?>

<script type="text/javascript">

	$('fieldset[id^="SourceLanguageTemplate"]').hide();
	populateConditions();

	function populateConditions() {
		var data = jQuery('#AdvanceSearch').val();
		if (!data)
			return;
		var arr = JSON.parse(data);
		var ts = $( ".add-source-langeuage" );
		for (var i = 0, len = arr.length; i < len; i++)
			addSourceLanguageFromObject(ts, arr[i]);
	}


	jQuery(function() {
		<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmCatalogItemConfigure').submit();
		<?php endif; ?>
	});

</script>