<?php if (!$this->allowed) {echo $this->translate('This partner is not allowed to use Reach'); return;} ?>
<p><?php echo $this->translate('Here you can configure your Catalog items'); ?></p>
<?php echo $this->filterForm; ?>
<?php //echo $this->newPartnerCatalogItemFolderForm; ?>
<div id="catalog_item_list_div" class="clear">
	<table>
		<thead>
		<tr>
			<th><?php echo $this->translate('ID'); ?></th>
			<th><?php echo $this->translate('Status'); ?></th>
			<th><?php echo $this->translate('System Name'); ?></th>
			<th><?php echo $this->translate('Publisher ID'); ?></th>
			<th><?php echo $this->translate('Vendor Partner ID'); ?></th>
			<th><?php echo $this->translate('Feature'); ?></th>
			<th><?php echo $this->translate('Type'); ?></th>
			<th><?php echo $this->translate('Turn Around Time'); ?></th>
			<th><?php echo $this->translate('Source Language'); ?></th>
			<th><?php echo $this->translate('Target Language'); ?></th>
			<th><?php echo $this->translate('Output Format'); ?></th>
			<th><?php echo $this->translate('Action'); ?></th>
		</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="12">
				<?php echo $this->paginator; ?>
			</td>
		</tr>
		</tfoot>
		<tbody>
		<?php foreach($this->paginator as /* Kaltura_Client_Reach_Type_VendorCatalogItem */ $catalogItem): ?>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><?php echo $catalogItem->id; ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorCatalogItemStatus', $catalogItem->status); ?></td>
				<td><?php echo $catalogItem->name; ?></td>
				<td><?php echo $catalogItem->systemName; ?></td>
				<td><?php echo $catalogItem->vendorPartnerId; ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceFeature', $catalogItem->serviceFeature); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceType', $catalogItem->serviceType); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceTurnAroundTime', $catalogItem->turnAroundTime); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceTurnAroundTime', $catalogItem->turnAroundTime); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceTurnAroundTime', $catalogItem->turnAroundTime); ?></td>
				<td><?php echo $this->enumTranslate('Kaltura_Client_Reach_Enum_VendorServiceTurnAroundTime', $catalogItem->turnAroundTime); ?></td>
				<td>
					<select class="options" onchange="doAction(this.value, <?php echo $catalogItem->id;?>, <?php echo $catalogItem->partnerId; ?>)">
						<option value=""><?php echo $this->translate('Select Action'); ?></option>
						<option value="remove" ><?php echo $this->translate('Remove'); ?></option>
					</select>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	jQuery('#filter_type').change(function() {
		if(this.value == "none") {
			$("#filter_text").css("display","none");
		}
		else {
			$("#filter_text").css("display","inline");
			$("#filter_text input").focus();
			if(this.value == "free")
				$("div.help").show();
			else
				$("div.help").hide();
		}
	});

	jQuery('#filter_type').change();

	function doAction(action, folderId) {
		if (action && eval('typeof ' + action) == 'function')
		{
			f = eval(action);
			Array.prototype.shift.apply(arguments);
			f.apply(this, arguments);
		}
		jQuery('select.options').val('');
	}
	function remove(catalogItemId,partnerId)
	{
		var ok = confirm('<?php echo $this->translate('Are you sure you want to remove Catalog Item from partner ?'); ?>');
		if (ok)
		{
			changeStatus(
				catalogItemId,
				<?php echo Kaltura_Client_Reach_Enum_VendorCatalogItemStatus::DELETED; ?>,
				partnerId,
				function() {
					alert('<?php echo $this->translate('Catalog Item removed');?>');
				}
			);
		}
	}

	function changeStatus(catalogItemId, status, partnerId, callback)
	{
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'PartnerCatalogItemSetStatusAction', 'catalogItemId' => 'CATALOGITEMID','partnerId' => 'PARTNERID', 'catalogItemStatus' => 'STATUS')); ?>';
		url = url.replace('STATUS', status);
		url = url.replace('CATALOGITEMID', catalogItemId);
		url = url.replace('PARTNERID', partnerId);
		jQuery.ajax({
			url: url,
			dataType: 'json',
			success: function(result) {
				if (result != 'ok')
					this.error(result);
				else
				{
					if (callback && (typeof callback == 'function'))
					{
						callback.apply(this);
					}
				}
				jQuery('#frmPaginator1').submit();
			},
			error: function(result) {
				alert(result);
			}
		});
	}

	function configureCatalogItems(partnerId, catalogItemType, catalogItemServiceType, catalogItemTurnAroundTime)
	{
		var paramsStr = '/new_partner_id/' + partnerId + '/new_catalog_item_type/' + catalogItemType + '/new_catalog_item_service_type/' + catalogItemServiceType + '/new_catalog_item_turn_around_time/' +catalogItemTurnAroundTime;

		loadCatalogItem(paramsStr);
	}

	function removeDisableTags()
	{
		jQuery('#isDefault').removeAttr('disabled');
		jQuery('#serviceType').removeAttr('disabled');
		jQuery('#turnAroundTime').removeAttr('disabled');
		jQuery('#source-language-fieldSet').removeAttr('disabled');
		jQuery('#target-language-fieldSet').removeAttr('disabled');
		jQuery('#output-formats-fieldSet').removeAttr('disabled');
		jQuery('#fieldset-pricing').removeAttr('disabled');
	}

	function addDisableTags()
	{
		jQuery('#source-language-fieldSet').attr('disabled', 'disabled');
		jQuery('#target-language-fieldSet').attr('disabled', 'disabled');
		jQuery('#output-formats-fieldSet').attr('disabled', 'disabled');
	}

	function loadCatalogItem(paramStr)
	{
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'PartnerCatalogItemConfigureAction', 'catalogItemPricingClz' => 'Null')); ?>' + paramStr;

		jQuery('#partner-catalog-item-configure-dialog').remove();
		dialogDiv = jQuery('<div id="partner-catalog-item-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');

		dialogDiv.dialog({
			bgiframe: true,
			modal: true,
			resizable: false,
			width: 600,
			height: 600,
			title: '<?php echo $this->translate('Catalog Item'); ?>',
			buttons: {
				'<?php echo $this->translate('Save'); ?>': function() {
					jQuery('.ui-widget-overlay').css('z-index', 1003 );
					jQuery('#loader').show();
					jQuery(this).find('#frmPartnerCatalogItemConfigure').submit();
				},
				'<?php echo $this->translate('Close'); ?>': function() {
					jQuery(this).dialog('close');
				}
			},
			close: function() {
				jQuery(this).dialog('destroy').remove();
			}
		});

		dialogDiv.load(
			url,
			null,
			function() {
				jQuery(this).find('#frmPartnerCatalogItemConfigure').ajaxForm({
					success: loadCatalogItemSuccess,
					iframe: true
				});
			}
		);
	}

	function loadCatalogItemSuccess(html) {
		if (jQuery(html).filter('#frmCatalogItemConfigure').hasClass('valid'))
		{
			dialogDiv.dialog('close');
			if (jQuery('#frmPaginator1').length){
				jQuery('#frmPaginator1').submit();
			}
			else {
				jQuery('#frmPartnerIdFilter').submit();
			}
		}
		jQuery('.ui-widget-overlay').css('z-index', 1000 );
		jQuery('#loader').hide();
		jQuery('#frmPartnerCatalogItemConfigure').replaceWith(html);
		jQuery('#frmPartnerCatalogItemConfigure').ajaxForm({
			success: loadCatalogItemSuccess,
			iframe: true
		});
	}
</script>