<?php if (!$this->allowed) {echo $this->translate('This partner is not allowed to use Reach'); return;} ?>
<p><?php echo $this->translate('Here you can view all partners using a specific Catalog Item'); ?></p>
<?php echo $this->filterForm; ?>

<div id="partners-by-catalog_item_list_div" class="clear">
	<table>
		<thead>
		<tr>
			<th>Select</th>
			<th><?php echo $this->translate('ID'); ?></th>
			<th><?php echo $this->translate('Catalog Item ID'); ?></th>
			<th><?php echo $this->translate('Partner ID'); ?></th>
			<th><?php echo $this->translate('Action'); ?></th>
		</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="17">
				<?php echo $this->paginator; ?>
			</td>
		</tr>
		</tfoot>
		<tbody>
		<?php if ($this->paginator)
			foreach($this->paginator as /* Kaltura_Client_Reach_Type_VendorCatalogItem */$partnerCatalogItem): ?>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><input type="checkbox" name="catalogItemsCheckBoxItems[]" id="$catalogItemsCheckBox-<?php echo $partnerCatalogItem->id; ?>" value="<?php echo $partnerCatalogItem->id; ?>" /></td>
				<td><?php echo $partnerCatalogItem->id; ?></td>
				<td><?php echo $partnerCatalogItem->catalogItemId; ?></td>
				<td><?php echo $partnerCatalogItem->partnerId ?? ' '; ?></td>
				<td>
					<select class="options" onchange="doAction(this.value, <?php echo $this->filterForm->getElement('filter_input')->getValue(); ?>, <?php echo $partnerCatalogItem->partnerId;?>)">
						<option value=""><?php echo $this->translate('Select Action'); ?></option>
						<option value="remove" ><?php echo $this->translate('Remove'); ?></option>
					</select>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<script type="text/javascript">

	$(function () {
		updateFiltersView();
	});
    
	jQuery('#filter_type').change(function() {
		if(this.value == "none") {
			$("#filter_text").css("display","none");
		}
		else {
			$("#filter_text").css("display","inline");
			$("#filter_text input").focus();
			if(this.value == "free")
				$("div.help").show();
			else
				$("div.help").hide();
		}
	});

	jQuery('#filter_type').change();

	function doAction(action, folderId) {
		if (action && eval('typeof ' + action) == 'function')
		{
			f = eval(action);
			Array.prototype.shift.apply(arguments);
			f.apply(this, arguments);
		}
		jQuery('select.options').val('');
	}

	function remove(catalogItemId,partnerId)
	{
		var ok = confirm('<?php echo $this->translate('Are you sure you want to remove Catalog Item from partner ?'); ?>');
		if (ok)
		{
			changeStatus(
				catalogItemId,
				<?php echo Kaltura_Client_Reach_Enum_VendorCatalogItemStatus::DELETED; ?>,
				partnerId,
				function() {
					alert('<?php echo $this->translate('Partner catalog Item removed');?>');
				}
			);
		}
	}

	function changeStatus(catalogItemIds, status, partnerId, callback)
	{
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'PartnerCatalogItemSetStatusAction', 'catalogItemIds' => 'CATALOGITEMIDS','partnerId' => 'PARTNERID', 'catalogItemStatus' => 'STATUS')); ?>';
		url = url.replace('STATUS', status);
		url = url.replace('CATALOGITEMIDS', catalogItemIds);
		url = url.replace('PARTNERID', partnerId);
		jQuery.ajax({
			url: url,
			dataType: 'json',
			success: function(result) {
				if (result != 'ok')
					this.error(result);
				else
				{
					if (callback && (typeof callback == 'function'))
					{
						callback.apply(this);
					}
				}
				jQuery('#frmPaginator1').submit();
			},
			error: function(result) {
				alert(JSON.stringify(result));
			}
		});
	}

</script>
