
<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>

<?php echo $this->form ?>

<script type="text/javascript">

	try{
		$('fieldset[id^="vendorProfileRuleTemplate"]').hide();
		populateRules();
	}
	catch (e)
	{
	}

	function populateRules() {
		var data = jQuery('#VendorProfileRules').val();
		if (!data)
			return;
		var arr = JSON.parse(data);
		var ts = $( ".add-rule" );
		for (var i = 0, len = arr.length; i < len; i++)
			addRuleFromObject(ts, arr[i]);
	}

	try{
		jQuery(function() {
		<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmVendorProfileConfigure').submit();
		<?php endif; ?>
	});
	}
	catch (e)
	{

	}

</script>