<p><b><?php echo 'Publisher ID: '.$this->partnerId; ?></b></p>
<p><?php echo $this->translate('partner-kmc-users intro text'); ?></p>
<div id="list_kmc_users_panel" class="panel">
	<table>
		<thead>
			<tr>
				<th><?php echo $this->translate('User ID'); ?></th>
				<th><?php echo $this->translate('User Name'); ?></th>
				<th><?php echo $this->translate('Email Address'); ?></th>
				<th><?php echo $this->translate('Role'); ?></th>
				<th><?php echo $this->translate('Action'); ?></th>
			</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="5">
			<?php echo $this->paginator; ?>
			</td>
		</tr>
		</tfoot>
		<tbody>
			<?php foreach($this->paginator as $user): ?>
			<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
				<td><?php echo $user->id; ?></td>
				<td><?php echo $user->fullName; ?></td>
				<td><?php echo $user->email; ?></td>
				<td>
					<?php
						echo $user->roleNames;
						if ($user->isAccountOwner) {
							echo ' (Account owner)';
						}					
					?>
				
				</td>
				<td>
					<select class="options" onchange="doAction(this.value, '<?php echo $user->partnerId; ?>','<?php echo $user->id; ?>')">
						<option value=""><?php echo $this->translate('Select Action'); ?></option>
						<option value="kmcLogin"><?php echo $this->translate('Login'); ?></option>
						<?php //if (Infra_AclHelper::isAllowed('partner','reset-user-password')): ?>
							<option value="resetUserPassword" ><?php echo $this->translate('Reset Password'); ?></option>
						<?php //endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<script type="text/javascript">

function kmcLogin(partnerId, userId) {
	var url = '<?php echo $this->url(array('controller' => 'partner', 'action' => 'kmc-redirect', 'partner_id' => '')); ?>' + partnerId + '/user_id/' + userId;
	window.open(url);
}

$( function() {
	var url = '<?php echo $this->url(array('controller' => 'partner', 'action' => 'kmc-users', 'partner_id' => $this->partnerId)); ?>';
	form = jQuery('#list_kmc_users_panel').find('form');
	form.attr('action', url);
	var theForm = form.get(0);
	theForm.submit = function() {
		jQuery('#partner-kmc-users-dialog').html('Loading...');
		jQuery.post(url, form.serialize(), function(data) {
			jQuery('#partner-kmc-users-dialog').html(data);
		});
		return false;
	};
});



function doAction(action, partnerId, userId) {
	userId = encodeURIComponent(userId);
	if (action && eval('typeof ' + action) == 'function')
	{
		f = eval(action);
		Array.prototype.shift.apply(arguments);
		f.apply(this, arguments);
	}
	jQuery('select.options').val('');
}

function resetUserPassword(partnerId, userId, pageHtml /* default = null */)
{
	pageHtml = (typeof pageHtml !== 'undefined') ? pageHtml : null;

	jQuery('#reset-user-password-dialog').remove();
	var url = '<?php echo $this->url(array('controller' => 'partner', 'action' => 'reset-user-password', 'partner_id' => '')); ?>' + partnerId + '/user_id/' + userId;
	
	var dialogDiv = jQuery('<div id="reset-user-password-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');
	
	dialogDiv.dialog({
		bgiframe: true,
		modal: true,
		resizable: false,
		width: 508,
		height: 300,
		title: '<?php echo $this->translate('Reset User Password'); ?>',
		buttons: {
			'<?php echo $this->translate('Close'); ?>': function() {
				jQuery(this).dialog('close');
			},
			'<?php echo $this->translate('Reset'); ?>': function() {
				jQuery(this).find('#frmKmcUsersResetPassword').submit();
			}
		}
	});
	
	dialogDiv.load(
		url, 
		null, 
		function() {
			if ( pageHtml != null ) {
				// Replace with the updated server page html, which includes a block
				// of error text, or an updated form with the 'valid' attribute
				jQuery('#resetUserPasswordPage').replaceWith( pageHtml );
			}

			if (jQuery('#frmKmcUsersResetPassword').hasClass('valid')) {
				jQuery('#reset-user-password-dialog').dialog('close');
				return;
			}

			jQuery(this).find('#frmKmcUsersResetPassword').ajaxForm({
				success: function( html ) {
					// Re-invoke this method with the server's result html
					resetUserPassword(partnerId, userId, html);
				},
				iframe: true
			});
		}
	);

}

</script>
