<?php if($this->errMessage) echo "<div class=\"error\">{$this->errMessage}</div>"; ?>
<?php $this->form->setAction($this->url(array('controller' => 'partner', 'action' => 'password-validation-rules'))); ?>

<fieldset class="password-validation">
	<legend>Password Validation Rules</legend>
	<table class="clear">
	<?php foreach ($this->regexList as $regexItem): ?>
		<?php $subForm = new Form_PasswordValidationRules(); ?>
		<?php $subForm->populateFromObject($regexItem); ?>
		<tr class="1">
		<?php echo $subForm->__toString(); ?>
		</tr>
	<?php endforeach; ?>
	</table>
	<a class="add-rule" href="javascript:;" onclick="addRegexRule(this);" >+ Add Regex</a>
</fieldset>

<script type="text/javascript">
	function addRegexRule(target) {
		<?php $subForm = new Form_PasswordValidationRules(); ?>
		<?php $subForm->setElementsBelongTo('password_validation_rules_REPLACE_RANDOM'); ?>
		var template = '<?php echo str_replace(array("\n", "\r"), '', $subForm->__toString()); ?>';
		var belongsRand = new Date().getTime();
		template = template.replace(/REPLACE_RANDOM/g, belongsRand);
		jQuery('.add-rule').before(template);
		jQuery(target).parent().find('[name=belongs]').val('password_validation_rules_'+belongsRand);
	}

    function passwordValidationRulesSaveButtonPressed()
    {
        var regexList = {};
        var regexObject = jQuery.parseJSON("{}");
        jQuery("fieldset[class=regex-rule]").each(function()
        {
           console.log($(this).find("input[id=regex]").val());
           console.log($(this).find("input[id=description]").val());
           var regex = $(this).find("input[id=regex]").val();
           var description = $(this).find("input[id=description]").val();
           regexObject[regex] = description;
		});
        // jQuery("input[id=regex]").each(function()
		// {
        //     console.log(this);
        //     console.log(this.value);
        //     regexList[this.value] = this.value;
        // });

        

        var index = 0;
        // for (regex in regexList)
        // {
        //     regexObject[index] = regex;
        //     index++;
        // }
        jQuery("input[name=password_structure_validations]").val(JSON.stringify(regexObject));
        updatedPasswordUI();
    }

    function updatedPasswordUI() {
        //createESearchlanguagesTable();
    }

    jQuery(document).ready(function() {
		<?php if ($this->formValid): ?>
        jQuery('#partner-configure-dialog').dialog('close');
        jQuery('#frmPaginator1').submit();
		<?php endif; ?>
    });
</script>