<?php if ($this->errMessage) echo "<div class=\"error\">{$this->errMessage}</div>"; ?>
<?php $this->form->setAction($this->url(array('controller' => 'partner', 'action' => 'password-validation-rules'))); ?>

<fieldset class="password-validation">
	<legend>Password Validation Rules</legend>
	<?php foreach ($this->regexList as $regexItem): ?>
		<?php $ruleSubForm = new Form_PasswordValidationRuleItem(); ?>
		<?php $ruleSubForm->populateFromObject($regexItem); ?>
		<?php echo $ruleSubForm->__toString(); ?>
	<?php endforeach; ?>
	<fieldset class="add-rule-fieldset">
		<a class="add-rule" href="javascript:;" onclick="addRegexRule();" >+ Add Regex</a>
	</fieldset>
</fieldset>

<script type="text/javascript">
	function addRegexRule()
	{
		<?php $ruleSubForm = new Form_PasswordValidationRuleItem(); ?>
		let subFormString = '<?php echo str_replace(array("\n", "\r"), '', $ruleSubForm->__toString()); ?>';
		jQuery("[class=add-rule-fieldset]").before(subFormString);
	}
</script>
