<?php if ($this->errMessage) echo "<div class=\"error\">{$this->errMessage}</div>"; ?>
<?php $this->form->setAction($this->url(array('controller' => 'partner', 'action' => 'password-validation-rules'))); ?>

<fieldset class="password-validation">
	<legend>Password Validation Rules</legend>
	<?php foreach ($this->regexList as $regexItem): ?>
		<?php $subForm = new Form_PasswordValidationRules(); ?>
		<?php $subForm->populateFromObject($regexItem); ?>
		<?php echo $subForm->__toString(); ?>
	<?php endforeach; ?>
	<fieldset class="add-rule-fieldset">
	<a class="add-rule" href="javascript:;" onclick="addRegexRule(this);" >+ Add Regex</a>
	</fieldset>
</fieldset>

<script type="text/javascript">
	function addRegexRule(target) {
		<?php $subForm = new Form_PasswordValidationRules(); ?>
		var template = '<?php echo str_replace(array("\n", "\r"), '', $subForm->__toString()); ?>';
		jQuery("[class=add-rule-fieldset]").before(template);
	}

    function passwordValidationRulesSaveButtonPressed()
    {
        var regexObject = jQuery.parseJSON("{}");
        jQuery("fieldset[class=regex-rule]").each(function() {
           console.log($(this).find("input[id=regex]").val());
           console.log($(this).find("input[id=description]").val());
           var regex = $(this).find("input[id=regex]").val();
           var description = $(this).find("input[id=description]").val();
           regexObject[regex] = description;
		});
        
        jQuery("input[name=password_structure_validations]").val(JSON.stringify(regexObject));
    }

    jQuery(document).ready(function() {
		<?php if ($this->formValid): ?>
        jQuery('#partner-configure-dialog').dialog('close');
        jQuery('#frmPaginator1').submit();
		<?php endif; ?>
    });
</script>