<div id=resetUserPasswordPage>

	<?php $this->form->setAction($this->url(array('controller' => 'partner', 'action' => 'reset-user-password'))); ?>

	<div class="resetUserPassword">
		<?php echo $this->translate('reset uses password first notification'); ?>
	</div>
	<div class="resetUserPassword">
		<?php echo $this->translate('reset users password second notification'); ?>
	</div>
	<div class="resetUserPassword">
		<?php echo $this->translate('reset users password third notofication'); ?>
	</div>
	
	<?php	
	echo $this->form;
	?>
	
	<?php if($this->errMessage): ?>
		<div class="error"><?php echo $this->errMessage ?></div><br/>
	<?php endif; ?>
</div>


