CREATE TABLE `batch_job_lock_suspend` (
  `id` int(11) NOT NULL,
  `entry_id` varchar(20) DEFAULT NULL,
  `object_type` int(6) DEFAULT NULL,
  `object_id` varchar(20) DEFAULT NULL,
  `partner_id` int(11) DEFAULT NULL,
  `dc` int(11) DEFAULT NULL,
  `job_type` int(6) DEFAULT NULL,
  `job_sub_type` int(6) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `priority` tinyint(4) NOT NULL,
  `urgency` tinyint(4) NOT NULL,
  `estimated_effort` bigint(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  `execution_attempts` tinyint(4) DEFAULT NULL,
  `scheduler_id` int(11) DEFAULT NULL,
  `worker_id` int(11) DEFAULT NULL,
  `batch_index` int(11) DEFAULT NULL,
  `expiration` datetime DEFAULT NULL,
  `start_at` datetime DEFAULT NULL,
  `batch_job_id` int(20) NOT NULL,
  `custom_data` text,
  PRIMARY KEY (`id`),
  KEY `dc_partner_job_type` (`dc`,`partner_id`,`job_type`,`job_sub_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8