UPDATE permission SET friendly_name = 'Base system admin permission' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_BASE' limit 1;
UPDATE permission SET friendly_name = 'Base publisher permission' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_BASE' limit 1;
UPDATE permission SET friendly_name = 'Publisher KMC access' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_KMC_ACCESS' limit 1;
UPDATE permission SET friendly_name = 'Publisher configure' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_CONFIG' limit 1;
UPDATE permission SET friendly_name = 'Publisher block and unblock' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_BLOCK' limit 1;
UPDATE permission SET friendly_name = 'Publisher remove' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_REMOVE' limit 1;
UPDATE permission SET friendly_name = 'Publisher add' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_ADD' limit 1;
UPDATE permission SET friendly_name = 'Publisher usage' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PUBLISHER_USAGE' limit 1;
UPDATE permission SET friendly_name = 'Manage users' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_USER_MANAGE' limit 1;
UPDATE permission SET friendly_name = 'System monitor' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_SYSTEM_MONITOR' limit 1;
UPDATE permission SET friendly_name = 'Developers tab' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_DEVELOPERS_TAB' limit 1;
UPDATE permission SET friendly_name = 'Batch Control tab' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_BATCH_CONTROL' limit 1;
UPDATE permission SET friendly_name = 'Batch Control in-progress' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_BATCH_CONTROL_INPROGRESS' limit 1;
UPDATE permission SET friendly_name = 'Batch Control failed' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_BATCH_CONTROL_FAILED' limit 1;
UPDATE permission SET friendly_name = 'Batch Control setup' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_BATCH_CONTROL_SETUP' limit 1;
UPDATE permission SET friendly_name = 'Storage' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_STORAGE' limit 1;
UPDATE permission SET friendly_name = 'Virus-Scan' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_VIRUS_SCAN' limit 1;
UPDATE permission SET friendly_name = 'E-Mail Integration' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_EMAIL_INGESTION' limit 1;
UPDATE permission SET friendly_name = 'Base content distribution' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_CONTENT_DISTRIBUTION_BASE' limit 1;
UPDATE permission SET friendly_name = 'Modify content distribution' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_CONTENT_DISTRIBUTION_MODIFY' limit 1;
UPDATE permission SET friendly_name = 'Manage permissions' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_PERMISSIONS_MANAGE' limit 1;
UPDATE permission SET friendly_name = 'Multi-Publisher console access' WHERE partner_id = -2 AND name = 'SYSTEM_ADMIN_MP_REDIRECT' limit 1;
UPDATE permission SET friendly_name = 'Bulk upload log download email' WHERE partner_id = 0 AND name = 'BULK_LOG_DOWNLOAD_EMAIL' limit 1;
UPDATE permission SET friendly_name = 'Content ingest into ready entry' WHERE partner_id = 0 AND name = 'CONTENT_INGEST_INTO_READY' limit 1;
UPDATE permission SET friendly_name = 'Content ingest' WHERE partner_id = 0 AND name = 'CONTENT_INGEST_BASE' limit 1;
UPDATE permission SET friendly_name = 'Drop Folder Base' WHERE partner_id = 0 AND name = 'dropFolder.CONTENT_INGEST_DROP_FOLDER_BASE' limit 1;
UPDATE permission SET friendly_name = 'Event Notification Template Service delete permission' WHERE partner_id = 0 AND name = 'eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_DELETE' limit 1;
UPDATE permission SET friendly_name = 'Event Notification Template Service manage permission' WHERE partner_id = 0 AND name = 'eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_MANAGE' limit 1;
UPDATE permission SET friendly_name = 'KMC read only access' WHERE partner_id = 0 AND name = 'KMC_READ_ONLY' limit 1;
UPDATE permission SET friendly_name = 'Manage custom data profile' WHERE partner_id = 0 AND name = 'CUSTOM_DATA_PROFILE_UPDATE' limit 1;
