ALTER TABLE upload_token MODIFY COLUMN `int_id` BIGINT(20) NOT NULL AUTO_INCREMENT, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE upload_token DROP PRIMARY KEY, ADD PRIMARY KEY (`id`,`created_at`);
