
<?php $this->form->setAction($this->url(array('controller' => 'plugin', 'action' => 'virus-scan-configure-action'))); ?>
	<?php
		echo $this->form;
	?>
	
<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>


<script type="text/javascript">                                         
	jQuery(document).ready(function() {
		<?php if ($this->formValid): ?>
			dialogDiv.dialog('close');
			jQuery('#frmPaginator1').submit();
		<?php endif; ?>
	});                                   
 </script>