<p><?php echo $this->translate('virus scan intro text'); ?></p>
<?php echo $this->virusScanFilterForm; ?>
<?php echo $this->newForm; ?>
   

<div id="results" class="clear">
	<table>
			<thead>
				<tr>
					<th><?php echo $this->translate('Status'); ?></th>
					<th><?php echo $this->translate('ID'); ?></th>
					<th><?php echo $this->translate('Name'); ?></th>
					<th><?php echo $this->translate('Publisher ID'); ?></th>
					<th><?php echo $this->translate('Engine'); ?></th>
					<th><?php echo $this->translate('Cleaning Policy'); ?></th>
					<th><?php echo $this->translate('Entry Type'); ?></th>
					<th><?php echo $this->translate('Create date'); ?></th>
					<th><?php echo $this->translate('Action'); ?></th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td colspan="8">
					<?php echo $this->paginator; ?>
					</td>
				</tr>
			</tfoot>
			<tbody>
				<?php foreach($this->paginator as $profile): ?>
				<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
					<td><?php echo $this->enumTranslate('Kaltura_Client_VirusScan_Enum_VirusScanProfileStatus', $profile->status);?></td>
					<td><?php echo $profile->id; ?></td>
					<td><?php echo $profile->name; ?></td>
					<td><?php echo $profile->partnerId; ?></td>
					<td><?php echo $profile->engineType; ?></td>
					<td><?php echo $this->enumTranslate('Kaltura_Client_VirusScan_Enum_VirusFoundAction', $profile->actionIfInfected);?></td>
					<td>
					<?php
						if (!empty($profile->entryFilter->typeEqual)) {
						 	echo $this->enumTranslate('Kaltura_Client_Enum_EntryType', $profile->entryFilter->typeEqual);
						}
						else if (!empty($profile->entryFilter->typeIn)) {
							$types = array_map('trim', explode(',', $profile->entryFilter->typeIn));
							$echoStr = '';
							foreach ($types as $type) {
								$echoStr .= $this->enumTranslate('Kaltura_Client_Enum_EntryType', $type).', ';
							}
							echo trim($echoStr, ' ,');
						}
						else {
							echo $this->translate('VIRUS_SCAN_ENTRY_TYPE_ALL');
						}
					?>
					</td>			
					<td><?php echo $this->dateFormat($profile->createdAt, Zend_Date::DATE_LONG); ?></td>
					<td>
						<select class="options" onchange="doAction(this.value, <?php echo $profile->id; ?>)">
								<option value=""><?php echo $this->translate('Select Action'); ?></option>
							<?php if ($profile->status == Kaltura_Client_VirusScan_Enum_VirusScanProfileStatus::ENABLED): ?>
								<option value="Disable" ><?php echo $this->translate('Disable'); ?></option>
							<?php elseif ($profile->status == Kaltura_Client_VirusScan_Enum_VirusScanProfileStatus::DISABLED): ?>
								<option value="Enable"><?php echo $this->translate('Enable'); ?></option>
							<?php endif; ?>
								<option value="Configure" ><?php echo $this->translate('Configure'); ?></option>
								<option value="Delete" ><?php echo $this->translate('Delete'); ?></option>						
						</select>
					</td>
					
				</tr>
				<?php endforeach; ?>
			</tbody>		
	</table>
		
</div>

<script type="text/javascript">
$(function(){
	addSubTitle('Virus Scan Profiles');
});

function doAction(action, profileId) {
	switch(action) {
		case 'Disable':
			changeProfileStatus('disable', profileId);
			break;
		case 'Enable':			
			changeProfileStatus('enable', profileId);
			break;
		case 'Configure':
			configure(profileId);
			break;
		case 'newVirusScanProfile':
			addNew(profileId);
			break;
		case 'Delete':
			deleteProfile(profileId);
			break;
	}
}



function changeProfileStatus(status, profileId) {
	var ok = false;
	ok = confirm('<?php echo $this->translate('are you sure you want to change virus scan profile status?'); ?>');
	if (ok) {
		url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-set-status-action'), null, true); ?>/profileId/' + profileId + '/status/' + status;
		jQuery.ajax({
			url: url,
			dataType: 'json',
			success: function(result) {
				if (result != 'ok')
					this.error();
				jQuery('#frmPaginator1').submit();
			},
			error: function() {
				if (status == 'disable')
					alert('<?php echo $this->translate('profile status was not changed to Disable');?>');
				else if (status == 'enable')
					alert('<?php echo $this->translate('profile status was not changed to Enable');?>');
			}
		});
	}
}

function resetOptions() {
	jQuery('table select.options').val('');
}

var dialogDiv;
function configure(profileId) {
	if (profileId == null){
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-configure-action')); ?>';
	}
	else{
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-configure-action', 'profileId' => '')); ?>' + profileId;
	}
	
	jQuery('#virus-scan-configure-dialog').remove();
	dialogDiv = jQuery('<div id="virus-scan-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');
	
	dialogDiv.dialog({
		bgiframe: true,
		modal: true,
		resizable: false,
		width: 500,
		height: 400,
		title: '<?php echo $this->translate('Virus Scan Profile'); ?>',
		buttons: {
			'<?php echo $this->translate('Save'); ?>': function() {
				jQuery(this).find('#frmVirusScanProfileConfig').submit();
			},
			'<?php echo $this->translate('Close'); ?>': function() {
				jQuery(this).dialog('close');
			}
		},
		close: function() {
			resetOptions();
		}	
	});
	dialogDiv.load(
		url, 
		null, 
		function() {
			jQuery(this).find('#frmVirusScanProfileConfig').ajaxForm({
				success: configureVirusScanProfileSuccess,
				iframe: true
			});
		}
	);
}

function addNew(partnerId) {
	
	var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-configure-action')); ?>' + '/new_partner_id/' + partnerId;
	
	jQuery('#virus-scan-configure-dialog').remove();
	dialogDiv = jQuery('<div id="virus-scan-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');
	
	dialogDiv.dialog({
		bgiframe: true,
		modal: true,
		resizable: false,
		width: 500,
		height: 400,
		title: '<?php echo $this->translate('Virus Scan Profile'); ?>',
		buttons: {
			'<?php echo $this->translate('Save'); ?>': function() {
				jQuery(this).find('#frmVirusScanProfileConfig').submit();
			},
			'<?php echo $this->translate('Close'); ?>': function() {
				jQuery(this).dialog('close');
			}
		},
		close: function() {
			resetOptions();
		}	
	});
	dialogDiv.load(
		url, 
		null, 
		function() {
			jQuery(this).find('#frmVirusScanProfileConfig').ajaxForm({
				success: configureVirusScanProfileSuccess,
				iframe: true
			});
		}
	);
}

function configureVirusScanProfileSuccess(html)
{
	jQuery('#frmVirusScanProfileConfig').replaceWith(html);
	jQuery('#frmVirusScanProfileConfig').ajaxForm({
		success: configureVirusScanProfileSuccess,
		iframe: true
	});
}

function deleteProfile(profileId)
{
	var ok = false;
	ok = confirm('<?php echo $this->translate('are you sure you want to delete profile?'); ?>');
	if (ok) {		
		url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-set-status-action'), null, true); ?>/profileId/' + profileId+ '/status/' + 'delete';
		jQuery.ajax({
			url: url,
			dataType: 'json',
			success: function(result) {
				if (result != 'ok')
					this.error();
				window.location = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'virus-scan-list-action'), null, true); ?>';
			},
			error: function() {
					alert('<?php echo $this->translate('profile status was not deleted');?>');
			}
		});
	}
	resetOptions();
}





</script>

