<form id="frmFlavorParams" enctype="application/x-www-form-urlencoded" method="post" class="inline-form" action="">
 <!--   <fieldset id="fieldset-frmFlavorParams" class="form">
        <dl>
            <dt id="Algorithm-label">Add Flavor Param</dt>
            <dd></dd>
            <dt><label for="name" class="optional">Name:</label>
                <input type="text" name="name" id="name" value=""/>
            </dt>
            <dt><label for="name">Video Codec:</label>
                <select name="video_codec" id="video_codec">
                    <option value="" label="NONE">NONE</option>
                    <option value="apch" label="APCH">APCH</option>
                    <option value="apcn" label="APCN">APCN</option>
                    <option value="apco" label="APCO">APCO</option>
                    <option value="apcs" label="APCS">APCS</option>
                    <option value="copy" label="COPY">COPY</option>
                    <option value="dnxhd" label="DNXHD">DNXHD</option>
                    <option value="dv" label="DV">DV</option>
                    <option value="flv" label="FLV">FLV</option>
                    <option value="h263" label="H263">H263</option>
                    <option value="h264" label="H264" selected="selected">H264</option>
                    <option value="h264b" label="H264B">H264B</option>
                    <option value="h264h" label="H264H">H264H</option>
                    <option value="h264m" label="H264M">H264M</option>
                    <option value="h265" label="H265">H265</option>
                    <option value="mpeg2" label="MPEG2">MPEG2</option>
                    <option value="mpeg4" label="MPEG4">MPEG4</option>
                    <option value="theora" label="THEORA">THEORA</option>
                    <option value="vp6" label="VP6">VP6</option>
                    <option value="vp8" label="VP8">VP8</option>
                    <option value="vp9" label="VP9">VP9</option>
                    <option value="wmv2" label="WMV2">WMV2</option>
                    <option value="wmv3" label="WMV3">WMV3</option>
                    <option value="wvc1a" label="WVC1A">WVC1A</option>
                </select>
            </dt>
            <dt><label for="name">Audio Codec:</label>
                <select name="audio_codec" id="audio_codec">
                    <option value="" label="NONE">NONE</option>
                    <option value="aac" label="AAC" selected="selected">AAC</option>
                    <option value="aache" label="AACHE">AACHE</option>
                    <option value="ac3" label="AC3">AC3</option>
                    <option value="amrnb" label="AMRNB">AMRNB</option>
                    <option value="copy" label="COPY">COPY</option>
                    <option value="mp3" label="MP3">MP3</option>
                    <option value="mpeg2" label="MPEG2">MPEG2</option>
                    <option value="pcm" label="PCM">PCM</option>
                    <option value="vorbis" label="VORBIS">VORBIS</option>
                    <option value="wma" label="WMA">WMA</option>
                    <option value="wmapro" label="WMAPRO">WMAPRO</option>
                </select>
            </dt>
            <dt><label for="name">Audio Codec:</label>
                <option value="3gp" label="_3GP">_3GP</option>
                <option value="applehttp" label="APPLEHTTP">APPLEHTTP</option>
                <option value="avi" label="AVI">AVI</option>
                <option value="bmp" label="BMP">BMP</option>
                <option value="copy" label="COPY">COPY</option>
                <option value="flv" label="FLV">FLV</option>
                <option value="hls" label="HLS">HLS</option>
                <option value="ismv" label="ISMV">ISMV</option>
                <option value="jpg" label="JPG">JPG</option>
                <option value="mkv" label="MKV">MKV</option>
                <option value="mov" label="MOV">MOV</option>
                <option value="mp3" label="MP3">MP3</option>
                <option value="mp4" label="MP4">MP4</option>
                <option value="mpeg" label="MPEG">MPEG</option>
                <option value="mpegts" label="MPEGTS">MPEGTS</option>
                <option value="ogg" label="OGG">OGG</option>
                <option value="ogv" label="OGV">OGV</option>
                <option value="pdf" label="PDF">PDF</option>
                <option value="png" label="PNG">PNG</option>
                <option value="swf" label="SWF">SWF</option>
                <option value="wav" label="WAV">WAV</option>
                <option value="webm" label="WEBM">WEBM</option>
                <option value="wma" label="WMA">WMA</option>
                <option value="wmv" label="WMV">WMV</option>
                <option value="wvm" label="WVM">WVM</option>
            </dt>
            <dt id="StringToManipulate-label"><label for="StringToManipulate" class="optional">String to
                    manipulate:</label></dt>
            <dd id="StringToManipulate-element">
                <textarea name="StringToManipulate" id="StringToManipulate" cols="48"
                          rows="3"><?php echo $this->str ?></textarea></dd>
            <button name="submit" id="submit" type="submit"><span>Submit</span></button>
        </dl>
    </fieldset>-->
</form>
<?php

echo $this->form; ?>
	
	
