<fieldset class="asset-distribution">
	<legend>Asset Distribution Rules</legend>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<a class="add-rule" href="javascript:;" onclick="addDistributionRule(this);" >+ Add Rule</a>
</fieldset>

<style type="text/css">
	#frmDistributionProfileConfig .asset-distribution { padding: 10px; }
	#frmDistributionProfileConfig .asset-distribution span.rule { font-size: 14px; font-weight: bold; }
	#frmDistributionProfileConfig .asset-distribution label { display: block; padding: 4px 0; }
	#frmDistributionProfileConfig .asset-distribution fieldset { height: auto; margin: 6px 0; padding: 10px; border: 1px solid #CCCCCC; }
	#frmDistributionProfileConfig .asset-distribution .add-condition,
	#frmDistributionProfileConfig .asset-distribution .remove-condition { margin: 4px 0; }
	#frmDistributionProfileConfig .asset-distribution .add-condition { float: left; }
	#frmDistributionProfileConfig .asset-distribution .remove-condition { float: right; }
	#frmDistributionProfileConfig .asset-distribution .remove-property { float: right; }
</style>

<script type="text/javascript">
	function addDistributionPropertyCondition(target, belongsTo) {
		<?php $subForm = new Form_AssetDistributionPropertyConditionSubForm(); ?>
		<?php $subForm->setElementsBelongTo('REPLACE_RANDOM1[asset_distribution_property_condition_REPLACE_RANDOM2]'); ?>
		var belongs = jQuery(target).parent().find('[name=belongs]').val();
		var template = '<?php echo str_replace(array("\n", "\r"), '', $subForm->__toString()); ?>';
		template = template.replace(/REPLACE_RANDOM1/g, belongs);
		template = template.replace(/REPLACE_RANDOM2/g, new Date().getTime());
		jQuery(target).before(template);
	}

	function addDistributionRule(target) {
		<?php $subForm = new Form_AssetDistributionRuleSubForm(); ?>
		<?php $subForm->setElementsBelongTo('asset_distribution_rule_REPLACE_RANDOM'); ?>
		var template = '<?php echo str_replace(array("\n", "\r"), '', $subForm->__toString()); ?>';
		var belongsRand = new Date().getTime();
		template = template.replace(/REPLACE_RANDOM/g, belongsRand);
		jQuery(target).before(template);
		jQuery(target).parent().find('[name=belongs]').val('asset_distribution_rule_'+belongsRand);
	}
</script>