<fieldset>
	<legend>Rule</legend>
	<label>Validation Error: <?php echo $this->element->getElement('validation_error'); ?></label>
	<label>Asset Required? <?php echo $this->element->getElement('required'); ?></label>
	<input type="hidden" name="belongs" value="<?php echo $this->element->getElementsBelongTo(); ?>" />
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($this->element->getElementsBelongTo().'['.$subForm->getName().']'); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<a class="add-condition" href="javascript:;" onclick="addDistributionPropertyCondition(this);" >+ Add Condition</a>
	<a class="remove-condition" href="javascript:;" onclick="$(this).parent().remove(); ">Remove</a>
</fieldset>