<?php $elements = $this->element->getElements(); ?>
<div class="field-config-row">
	<div class="field-config-head">
		<?php echo $this->element->getElement('override'); ?>
		<?php echo $this->element->getElement('fieldName'); ?>
		<?php echo $this->element->getElement('fieldNameForView'); ?>
	</div>
	<div class="field-config-edit">
		<dl>
			<?php echo $this->element->getElement('userFriendlyFieldName'); ?>
			<?php echo $this->element->getElement('entryMrssXslt'); ?>
			<?php echo $this->element->getElement('isRequired'); ?>
			<?php echo $this->element->getElement('type'); ?>
			<dt><label for="<?php echo $this->element->getElement('triggerDeleteOnError')->getId(); ?>"><?php echo $this->element->getElement('triggerDeleteOnError')->getLabel(); ?></label></dt>
			<dd><?php echo $this->element->getElement('triggerDeleteOnError'); ?></dd>
			<dt><label for="<?php echo $this->element->getElement('updateOnChange')->getId(); ?>"><?php echo $this->element->getElement('updateOnChange')->getLabel(); ?></label></dt>
			<dd><?php echo $this->element->getElement('updateOnChange'); ?><?php echo $this->element->getElement('updateParamsArrayString'); ?></dd>
		</dl>
	</div>
</div>