<div id="addItemXpath">
	<a href="#" class="add-item-xpath">+ Add </a>
</div>

<script type="text/javascript">
$(function() {
	$('#fieldset-itemXpathsToExtend_group input').attr('name', 'itemXpathsToExtend[]');
	$("[id$='includeCategoryInMrss']").attr('name', 'itemXpathsToExtend[includeCategoryInMrss]');
	$("[id$='includeCategoryParentInMrss']").attr('name', 'itemXpathsToExtend[includeCategoryParentInMrss]');

	$("#includeCategoryInMrss-element").before($("#addItemXpath"));
	
	$('a.add-item-xpath').click(function() {
		$new = $('#fieldset-itemXpathsToExtend_group input:first').parent().clone();
		$new.find('input').val('');
		$(this).parent().before($new);
		return false;
	});

	$("[id$='includeCategoryInMrss']").click(function() {
		var enableCategoryExtend  = $(this).is(':checked');
		if(!enableCategoryExtend){
			$("[id$='includeCategoryParentInMrss']").prop('disabled', true);
			$("[id$='includeCategoryParentInMrss']").val(false);
			$("[for$='includeCategoryParentInMrss']").css('color','grey');
		}
		else{
			$("[id$='includeCategoryParentInMrss']").prop('disabled', false);
			$("[for$='includeCategoryParentInMrss']").css('color','black');
		}
	});

	var enableCategoryExtend = $("[id$='includeCategoryInMrss']").is(':checked');
	if(!enableCategoryExtend){
		$("[id$='includeCategoryParentInMrss']").prop('disabled', true);
		$("[for$='includeCategoryParentInMrss']").css('color','grey');
	}
});
</script>

<style>
	#fieldset-itemXpathsToExtend_group div { margin: 10px 0; } 
	#fieldset-itemXpathsToExtend_group input { width: 100%; }
	#fieldset-itemXpathsToExtend_group input[id$="includeCategoryInMrss"] { width:14px !important; float:left; margin: 2px 4px 0 0;}
	#fieldset-itemXpathsToExtend_group input[id$="includeCategoryParentInMrss"] { width:14px !important; float:left; margin: 2px 4px 5px 0;}
	#includeCategoryParentInMrss-element {margin-top:4px;}
</style>