<?php echo $this->content; ?>
<script type="text/javascript">
	$(function() {
		$('input.override').change(function() {
			var $editSection = $(this).parents('.field-config-row').find('.field-config-edit');
			if ($(this).is(':checked'))
				$editSection.show(0);
			else
				$editSection.hide();
		});

		$('input.update-on-change').change(function() {
			var $editSection = $(this).parent().find('input[type=text]');
			if ($(this).is(':checked'))
				$editSection.show();
			else
				$editSection.hide();
		});

		$('input.override:checked').change();
		$('input.update-on-change:checked').change();
	});
</script>