<script type="text/javascript">
	var $metadataConfigRow;
	$(function() {
		var addMetadataButtonHtml = '';
		addMetadataButtonHtml += '<div id="metadataConfigAddButton" class="field-config-row">';
		addMetadataButtonHtml += '	<div class="field-config-head">';
		addMetadataButtonHtml += '		<a href="#">+ Add </a>';
		addMetadataButtonHtml += '	</div>';
		addMetadataButtonHtml += '</div>';

		var $addMetadataButtonHtml = $(addMetadataButtonHtml);
		$addMetadataButtonHtml.find('a').click(onAddMetadataButtonClick);
		$('#frmDistributionProfileConfig #fieldset-fieldConfigArray').append($addMetadataButtonHtml);
		$metadataConfigRow = $('#frmDistributionProfileConfig input[value=FWMETADATA]').parent().parent();
		$metadataConfigRow.hide();
	});

	function onAddMetadataButtonClick()
	{
		var $new = $metadataConfigRow.clone(true);
		$new.addClass('metadata-field-config');
		$new.find('input').each(function() {
			var name = $(this).attr('name');
			$(this).attr('name', name.replace('FWMETADATA', 'FWMETADATA_'));
		});
		$('#metadataConfigAddButton').before($new.show());
		reorganizeMetadataFields();
		return false;
	}

	function reorganizeMetadataFields()
	{
		var index = 1;
		$('.field-config-row').each(function() {
			var name = $(this).find('input[type=hidden]:first').attr('name');
			if (!name)
				return;
			
			if (name.indexOf('FWMETADATA_') == -1)
				return;
			
			$(this).find('input').each(function() {
				var name = $(this).attr('name');
				$(this).attr('name', name.replace(/FWMETADATA_[0-9]*/, 'FWMETADATA_' + index));
			});

			$(this).find('.field-config-head input[type=hidden], .field-config-head input[type=text]').val('FWMETADATA_' + index);
			
			index++;
		});
	}
		
</script>