<form
	action="<?php echo $this->url ( array ('controller' => 'delivery', 'action' => 'configure-delivery-profile' )); ?>"
	method="post" enctype="application/x-www-form-urlencoded"
	id="frmDeliveryProfileConfig" class="<?php echo ($this->formValid) ? 'valid' : 'invalid'; ?>">

<?php echo $this->form; ?>

<script type="text/javascript">
jQuery('[class=commentForm]').toggle();

jQuery(document).ready(function() {

	<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmPartnerFilter').submit();
	<?php endif; ?>
});

function replaceTokenizerForm() {

	var tokenizerClass = jQuery('#tokenizer-objectType').val();
	var url = '<?php echo $this->url(array('controller' => 'delivery', 'action' => 'get-tokenizer-form', 'tokenizerClz' => 'TOKENIZER')); ?>';
	url = url.replace('TOKENIZER', tokenizerClass);
	
	subform = jQuery('#tokenizer-element');
	subform.load(
			url, 
			null, 
			function(html) {
				jQuery('#tokenizer-element').replaceWith(jQuery.parseHTML(html)[1]);
				jQuery('#tokenizer-objectType').change(replaceTokenizerForm);
			}
	);
}

jQuery('#tokenizer-objectType').change(replaceTokenizerForm);

function replaceRecognizerForm() {

	var recognizerClass = jQuery('#recognizer-objectType').val();
	var url = '<?php echo $this->url(array('controller' => 'delivery', 'action' => 'get-recognizer-form', 'recognizerClz' => 'RECOGNIZER')); ?>';
	url = url.replace('RECOGNIZER', recognizerClass);
	
	subform = jQuery('#recognizer-element');
	subform.load(
			url, 
			null, 
			function(html) {
				jQuery('#recognizer-element').replaceWith(jQuery.parseHTML(html)[1]);
				jQuery('#recognizer-objectType').change(replaceRecognizerForm);
			}
	);
}

jQuery('#recognizer-objectType').change(replaceRecognizerForm);
</script>
</form>


