<?php
/**
 * @package plugins.quickPlayDistribution
 * @subpackage model.enum
 */ 
interface QuickPlayDistributionField extends BaseEnum
{
	const TITLE = 'TITLE';
	const DESCRIPTION = 'DESCRIPTION';
	const GUID = 'GUID';
	const CATEGORY = 'CATEGORY';
	const PUB_DATE = 'PUB_DATE';
	const QPM_KEYWORDS = 'QPM_KEYWORDS';
	const QPM_PRICE_ID = 'QPM_PRICE_ID';
	const QPM_UPDATE_DATE = 'QPM_UPDATE_DATE';
	const QPM_EXPIRY_DATE = 'QPM_EXPIRY_DATE';
	const QPM_SORT_ORDER = 'QPM_SORT_ORDER';
	const QPM_GENRE = 'QPM_GENRE';
	const QPM_COPYRIGHT = 'QPM_COPYRIGHT';
	const QPM_ARTIST = 'QPM_ARTIST';
	const QPM_DIRECTOR = 'QPM_DIRECTOR';
	const QPM_PRODUCER = 'QPM_PRODUCER';
	const QPM_EXP_DATE_PADDING = 'QPM_EXP_DATE_PADDING';
	const QPM_ON_DEVICE_EXPIRATION_PADDING = 'QPM_ON_DEVICE_EXPIRATION_PADDING';
	const QPM_ON_DEVICE_EXPIRATION = 'QPM_ON_DEVICE_EXPIRATION';
	const QPM_GROUP_CATEGORY = 'QPM_GROUP_CATEGORY';
	const QPM_NOTES = 'QPM_NOTES';
	const QPM_RATING = 'QPM_RATING';
	const QPM_RATING_SCHEMA = 'QPM_RATING_SCHEMA';
	const ENCLOSURE_CONTENT_ENCODING_PROFILE= 'ENCLOSURE_CONTENT_ENCODING_PROFILE';
	const ENCLOSURE_THUMBNAIL_ENCODING_PROFILE= 'ENCLOSURE_THUMBNAIL_ENCODING_PROFILE';
}