<?php
/**
 * @package plugins.schedule
 * @subpackage api.objects
 */
class KalturaSimulatedLiveEntryScheduleEvent extends KalturaEntryScheduleEvent
{
	public function getScheduleEventType()
	{
		ScheduleEventType::SIMU_LIVE;
	}

	public function validateForInsert($propertiesToSkip = array())
	{
		$this->validatePropertyNotNull('startDate');
		$this->validatePropertyNotNull('endDate');
	}

	public function toInsertableObject($object_to_fill = null, $props_to_skip = array())
	{
		return parent::toInsertableObject($object_to_fill, $props_to_skip); // TODO: Change the autogenerated stub
	}


	public function toObject($object_to_fill = null, $props_to_skip = array())
	{
		if (!$object_to_fill)
			$object_to_fill = new SimulatedLiveEntryScheduleEvent();
		return parent::toObject($object_to_fill, $props_to_skip);
	}


}