<?php
$this->headScript()	->setIndent("	")
                    ->appendFile($this->baseUrl('codemirror2/lib/codemirror.js'))
                    ->appendFile($this->baseUrl('codemirror2/mode/xml/xml.js'))
                    ->appendFile($this->baseUrl('codemirror2/lib/util/formatting.js'));

$this->headLink()   ->setIndent("	")
                    ->appendStylesheet($this->baseUrl('codemirror2/theme/cobalt.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/eclipse.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/elegant.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/monokai.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/neat.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/night.css'))
    ->appendStylesheet($this->baseUrl('codemirror2/theme/rubyblue.css'))

                    ->appendStylesheet($this->baseUrl('codemirror2/lib/codemirror.css'));
?>
<div id="xslt-loader"></div>
<div id="menu">
    <label>Entry ID: <input id="entry-id" type="text" value="<?php echo $this->entryId;?>"/></label>
    <button id="reload">Reload</button>
    <div class="floatr">
        <button id="test">Test</button>
        <button id="save">Save</button>
    </div>
</div>
<div id="xml-wrap">
    <textarea id="xml"><?php echo $this->xml; ?></textarea>
</div>

<div id="xslt-wrap">
    <textarea id="xslt"></textarea>
</div>

<div id="result-wrap">
    <textarea id="result"></textarea>
</div>

<script type="text/javascript">
    (function(){
        var xmlEditor;
        var xsltEditor;
        var resultEditor;
        var defaultOptions = {
            mode: {
                name: "xml"
            },
            lineNumbers: true,
            theme: 'rubyblue'
        };

        (function() {
            initXmlEditor();
            initXsltEditor();
            initResultEditor();
            registerToWindowResize();
            onWindowResize();
            bindButtons();
        })();

        function initXmlEditor() {
            xmlEditor = getEditorForTextArea('xml', {readOnly: true});
            CodeMirror.commands["selectAll"](xmlEditor);
            var range = { from: xmlEditor.getCursor(true), to: xmlEditor.getCursor(false) };
            xmlEditor.autoFormatRange(range.from, range.to);
            xmlEditor.scrollTo(0, 0);
        }

        function initXsltEditor() {
            xsltEditor = getEditorForTextArea('xslt');
            var defaultXslt = '<\?xml version="1.0" encoding="UTF-8"?>\n';
            defaultXslt += '<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">\n';
            defaultXslt += '\t<xsl:output omit-xml-declaration="yes" method="xml" />\n';
            defaultXslt += '\t<xsl:template match="item">\n';
            defaultXslt += '\t\t<name>The name of my entry is "<xsl:value-of select="title"/>"</name>\n';
            defaultXslt += '\t</xsl:template>\n';
            defaultXslt += '</xsl:stylesheet>'
            xsltEditor.setValue(defaultXslt);
        }

        function initResultEditor() {
            resultEditor = getEditorForTextArea('result', {readOnly: true});
        }

        function getEditorForTextArea(id, options) {
            return CodeMirror.fromTextArea(document.getElementById(id), jQuery.extend({}, defaultOptions, options));
        }

        function registerToWindowResize() {
            jQuery(window).resize(onWindowResize);
        }

        function bindButtons() {
            jQuery('#reload').click(onReloadClick);
            jQuery('#test').click(onTestClick);
            jQuery('#save').click(onSaveClick);
        }

        function onWindowResize() {
            var menuHeight = jQuery('#menu').outerHeight(true);
            var height = jQuery(window).height() - menuHeight;
            jQuery('#xml-wrap .CodeMirror-scroll').height(height);
            jQuery('#xslt-wrap .CodeMirror-scroll').height(Math.floor(height / 2));
            jQuery('#result-wrap .CodeMirror-scroll').height(Math.floor(height / 2));
        }

        function onReloadClick() {
            var baseUrl = "<?php echo $this->url(array('controller' => 'plugin', 'action' => 'XsltTesterAction', 'entry-id' => ''), null, true); ?>";
            window.location = baseUrl + jQuery('#entry-id').val();
        }

        function onTestClick() {
            showLoader();
            jQuery.ajax({
                url: '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'XsltTesterApiAction', 'entry-id' => $this->entryId), null, true); ?>',
                dataType: 'json',
                data: {
                    xslt: xsltEditor.getValue()
                },
                type: 'POST',
                success: onTestSuccess,
                error: onTestError
            });
        }

        function onSaveClick() {

        }

        function onTestSuccess(data) {
            hideLoader();
            if (data.result) {
                resultEditor.setValue(data.result);
            }
            else {
                onTestError(data);
            }
        }

        function onTestError(data) {
            hideLoader();
            if (data.error) {
                alert(data.error);
            }
            else {
                alert('An error occurred')
            }
        }

        function showLoader() {
            jQuery('#xslt-loader').css('visibility', 'visible');
        }

        function hideLoader() {
            jQuery('#xslt-loader').css('visibility', 'hidden');
        }
    })();
</script>
<style>
    #menu { padding: 6px; }
    #xml-wrap { float: left; width: 50%; }
    #xslt-wrap { float: right; width: 50%; }
    #result-wrap { float: right; width: 50%; }
    .floatr { float: right; }
    #xslt-loader { float: right; margin: 9px; visibility: hidden; background-image: url('<?php echo $this->baseUrl('images/ajax-loader2.gif'); ?>'); width: 16px; height: 16px; }
</style>