<?php if($this->element->getValue()) : ?>
	<?php if ($this->element->hasToken){ ?>
		<script>
			function showReAuthenticate()
			{
				document.getElementById("api_authorize_url_div").style.display = "block";
				document.getElementById("re_authenticate_link").style.display = "none";
			}
		</script>
		<fieldset>
			<dt>
				<label>Authorize API Access</label>
			</dt>
			<dd>
				<a href="#" onclick="showReAuthenticate()" id="re_authenticate_link">Re-authenticate</a>
				<div id="api_authorize_url_div" style="display:none" >
					<input type="text" value="<?php echo $this->element->getValue(); ?>" id="api_authorize_url">
					<p class="description">Send this link to the person who has access to the KMC and the YouTube channel. They should login using his KMC credentials and then authenticate at Google using his Google Account that is linked with his YouTube channel. This authorization process is only required when using playlists.</p>
				</div>
			</dd>
		</fieldset>
	<?php } else { ?>
		<fieldset>
			<dt>
				<label>Authorize API Access</label>
			</dt>
			<dd>
				<input type="text" value="<?php echo $this->element->getValue(); ?>" id="api_authorize_url">
				<p class="description">Send this link to the person who has access to the KMC and the YouTube channel. They should login using his KMC credentials and then authenticate at Google using his Google Account that is linked with his YouTube channel. This authorization process is only required when using playlists.</p>
			</dd>
		</fieldset>
	<?php } // hasToken ?>
<?php endif; ?>