<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php endif; ?>


<?php
	$this->form->setAction($this->url(array('controller' => 'plugin', 'action' => 'MediaRepurposingConfigureAction')));
	echo $this->form;
?>

<style type="text/css">
	#frmMediaRepurposingConfigure textarea {  height: 5em;  width: 25em;  }
</style>


<script type="text/javascript">
	
	var filterStatus = 0;
	var alwaysDisplay = [];
	init();

	function init() {
		//hide template
		$('dd[id^="MR_tasksDataTemplate_"]').hide();
		$('fieldset[id^="MR_SearchConditionTemplate"]').hide();

		hideEmptyFilterFields();
		populateTasks();
		populateConditions();
		checkIfError();
		populateDates();
	}


	function changeFilterStatus() {
		let button = jQuery('#expandFilter');
		if (filterStatus) {
			hideEmptyFilterFields();
			button.text("Expand");
		} else {
			hideEmptyFilterFields(false);
			button.text("Hide un-used");
		}
		filterStatus = !filterStatus;
	}
	
	function hideEmptyFilterFields(hide = true) {
		let f = jQuery('#frmMediaRepurposingConfigure');
		f.find( "input[id^=FilterParams_],select[id^=FilterParams_]").each(function(idx) {
			var val = $(this).val();
			var name = $( this ).attr("name");
			if (alwaysDisplay.includes(name.replace("FilterParams_", "")))
				return;
			if (!val.length || val == 'N/A') {
				if (hide) {
					$( this ).hide();
					jQuery('#' + name + '-label').hide();
				} else {
					$( this ).show();
					jQuery('#' + name + '-label').show();
				}
			}
		});
	}

	function checkIfError() {
		var x = jQuery('#generalTitle').val();
		if (x) {
			alert('Form was invalid, didn\'t saved');
			x.attr('value',0);
		}
	}
	

	function populateTasks() {
		var data = jQuery('#TasksData').val();
		if (!data)
			return;
		var arr = JSON.parse(data);
		var ts = $( ".add-task" );

		for (var i = 0, len = arr.length; i < len; i++)
			addTaskFromObject(ts, arr[i]);
	}

	function populateConditions() {
		var data = jQuery('#AdvanceSearch').val();
		if (!data)
			return;
		var arr = JSON.parse(data);
		var ts = $( ".add-cond" );
		for (var i = 0, len = arr.length; i < len; i++)
			addCondFromObject(ts, arr[i]);
	}
	
	function populateDates() {
		var d = new Date(0);
		
		let f = jQuery('#frmMediaRepurposingConfigure');
		f.find( "input[innertype=integer]").each(function(idx) {
			var val = parseInt($(this).val());
			if (isNaN(val) || val < 315360000) // 10 Year (max relative time)	315360000
				return;
			d.setUTCSeconds(val);
			$(this).val(d.toISOString().slice(0,10).replace(/-/g,"."));
		});
	}


jQuery(function() {
	<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#frmPaginator1').submit();
	<?php endif; ?>
});

</script>

