<?php if ($this->notFound == true): ?>
<p class="error"><?php echo $this->translate('Report not found'); ?></p>
<?php else: ?>
<?php echo $this->form; ?>
<?php endif; ?>

<script type="text/javascript">

jQuery(function() {
	var codeMirrorOptions = {
	    parserfile: "parsesql.js",
	    stylesheet: "<?php echo $this->baseUrl("css/sqlcolors.css"); ?>",
	    path: "<?php echo $this->baseUrl("codemirror/js/")?>",
	    continuousScanning: 500,
	    lineNumbers: true,
		textWrapping: false,
		initCallback: function() {}
	};

	var codeMirrorEditor = CodeMirror.fromTextArea('query', codeMirrorOptions);

	jQuery('form.report-form').submit(function() {
		jQuery('#query').val(codeMirrorEditor.getCode());
	});
});

jQuery(document).ready(function() {
	<?php if ($this->formValid): ?>
		dialogDiv.dialog('close');
		jQuery('#report-dialog').dialog('close')
		jQuery('#frmPaginator1').submit();
	<?php endif; ?>
});

</script>