
<?php if($this->errMessage): ?>
<div class="error"><?php echo $this->errMessage ?></div>
<?php endif; ?>

<?php echo $this->form ?>

<script type="text/javascript">

var newUserParameterIndex = 0;
function newUserParameter() {
	var currentIndex = newUserParameterIndex;
	var jqNewUserParameterTemplate = jQuery("#frmUserParameter");
	
	var jqNewUserParameterForm = jqNewUserParameterTemplate.clone();
	jqNewUserParameterForm.attr("id", "frmUserParameter_" + currentIndex);
	jqNewUserParameterForm.addClass("user-parameter");

	var jqUserParameterKey = jqNewUserParameterForm.find('[name="userParameterKey"]');
	jqUserParameterKey.attr('name', 'userParameterKey[' + currentIndex + ']');

	var jqUserParameterValue = jqNewUserParameterForm.find('[name="userParameterValue"]');
	jqUserParameterValue.attr('name', 'userParameterValue[' + currentIndex + ']');

	var jqUserParameterButton = jqNewUserParameterForm.find('[name="removeUserParameterButton"]');
	jqUserParameterButton.click(function(){
		jqNewUserParameterForm.remove();
	});
	
	jqNewUserParameterTemplate.after(jqNewUserParameterForm);
	jqNewUserParameterForm.show();

	newUserParameterIndex++;
}

function automaticEnabled(enabled) {
	if(enabled)	{
		jQuery('#frmAutomaticConfig').show();
	}
	else {
		jQuery('#frmAutomaticConfig').hide();
	}
}

if (typeof(jQuery) != 'undefined') {
	jQuery(function() {
		automaticEnabled(jQuery('#automatic_dispatch_enabled').attr('checked'));
	});
}

jQuery(document).ready(function() {
	<?php if ($this->formValid): ?>
		jQuery('#partner-configure-dialog').dialog('close');
		jQuery('#frmPaginator1').submit();
	<?php endif; ?>
});

</script>

<?php 
	foreach($this->plugins as $phtml => $pluginData)
		echo $this->partial($phtml, $pluginData);
?>
