<fieldset>
	<?php echo $this->searchType; ?>
	<?php echo $this->entryId; ?>
	<?php echo $this->search; ?> 
	<?php if(Infra_Support::isAdminEnabled()): ?> 
	<dl>
		<dt id="entryFile-label"><label for="entryFile" class="optional"><?php echo $this->translate('entry-investigate entry upload support'); ?>:</label></dt> 
		<dd><?php echo $this->entryFile; ?></dd>
	</dl>
	<?php endif; ?>
	<?php 
		echo $this->submitAction;
		echo $this->partnerId;
		echo $this->actionFlavorAssetId;
		echo $this->actionJobId;
		echo $this->actionJobType;
	?>
</fieldset>