
<div>
<label title="<?php echo $this->translate('gallery filter partner tooltip') ?>"><?php echo $this->translate('gallery filter partner label'); ?><?php echo $this->partnerId; ?></label>
<label title="<?php echo $this->translate('gallery filter entry tooltip') ?>"><?php echo $this->translate('gallery filter entry label'); ?><?php echo $this->id_in; ?></label>
</div>

<?php 
	foreach($this->enumFields as $fieldName => $enumClass)
	{
    	$reflect = new ReflectionClass($enumClass);
    	
    	echo '<hr noshade="noshade" size="1" /><div>';
    	echo "<label>{$this->$fieldName} " . $this->translate("gallery filter $fieldName") . '</label>';
    	echo "<ul id=\"{$fieldName}_list\">";
    	
		foreach($reflect->getConstants() as $const)
		{
	        $field = str_replace('-', '_', "{$fieldName}_{$const}");
	        $label = $this->enumTranslate($enumClass, $const);
	        
	        echo "<li><label>{$this->$field} $label ($const)</label>";
		}

		echo "</ul></div>";
	}
?>

<div>
<?php echo $this->search; ?>
</div>

<script type="text/javascript">

function toogleAll(fieldName){
	var $field = $('#' + fieldName);
	var checked = $field.attr('checked');
	var $inputs = $('#' + fieldName + '_list').find('input[type=checkbox]');
	$inputs.attr('checked', checked);
}
	
</script>