<?php
// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2011  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================

class Kaltura_Client_TypeMap
{
	private static $map = array(
		'KalturaAccessControl' => 'Kaltura_Client_Type_AccessControl',
		'KalturaAccessControlAction' => 'Kaltura_Client_Type_AccessControlAction',
		'KalturaAccessControlBaseFilter' => 'Kaltura_Client_Type_AccessControlBaseFilter',
		'KalturaAccessControlBlockAction' => 'Kaltura_Client_Type_AccessControlBlockAction',
		'KalturaAccessControlContextTypeHolder' => 'Kaltura_Client_Type_AccessControlContextTypeHolder',
		'KalturaAccessControlFilter' => 'Kaltura_Client_Type_AccessControlFilter',
		'KalturaAccessControlListResponse' => 'Kaltura_Client_Type_AccessControlListResponse',
		'KalturaAccessControlPreviewAction' => 'Kaltura_Client_Type_AccessControlPreviewAction',
		'KalturaAccessControlProfile' => 'Kaltura_Client_Type_AccessControlProfile',
		'KalturaAccessControlProfileBaseFilter' => 'Kaltura_Client_Type_AccessControlProfileBaseFilter',
		'KalturaAccessControlProfileFilter' => 'Kaltura_Client_Type_AccessControlProfileFilter',
		'KalturaAccessControlProfileListResponse' => 'Kaltura_Client_Type_AccessControlProfileListResponse',
		'KalturaAccessControlScope' => 'Kaltura_Client_Type_AccessControlScope',
		'KalturaAdminUser' => 'Kaltura_Client_Type_AdminUser',
		'KalturaAdminUserBaseFilter' => 'Kaltura_Client_Type_AdminUserBaseFilter',
		'KalturaAdminUserFilter' => 'Kaltura_Client_Type_AdminUserFilter',
		'KalturaAmazonS3StorageProfile' => 'Kaltura_Client_Type_AmazonS3StorageProfile',
		'KalturaAmazonS3StorageProfileBaseFilter' => 'Kaltura_Client_Type_AmazonS3StorageProfileBaseFilter',
		'KalturaAmazonS3StorageProfileFilter' => 'Kaltura_Client_Type_AmazonS3StorageProfileFilter',
		'KalturaApiActionPermissionItem' => 'Kaltura_Client_Type_ApiActionPermissionItem',
		'KalturaApiActionPermissionItemBaseFilter' => 'Kaltura_Client_Type_ApiActionPermissionItemBaseFilter',
		'KalturaApiActionPermissionItemFilter' => 'Kaltura_Client_Type_ApiActionPermissionItemFilter',
		'KalturaApiParameterPermissionItem' => 'Kaltura_Client_Type_ApiParameterPermissionItem',
		'KalturaApiParameterPermissionItemBaseFilter' => 'Kaltura_Client_Type_ApiParameterPermissionItemBaseFilter',
		'KalturaApiParameterPermissionItemFilter' => 'Kaltura_Client_Type_ApiParameterPermissionItemFilter',
		'KalturaAsset' => 'Kaltura_Client_Type_Asset',
		'KalturaAssetBaseFilter' => 'Kaltura_Client_Type_AssetBaseFilter',
		'KalturaAssetFilter' => 'Kaltura_Client_Type_AssetFilter',
		'KalturaAssetParams' => 'Kaltura_Client_Type_AssetParams',
		'KalturaAssetParamsBaseFilter' => 'Kaltura_Client_Type_AssetParamsBaseFilter',
		'KalturaAssetParamsFilter' => 'Kaltura_Client_Type_AssetParamsFilter',
		'KalturaAssetParamsOutput' => 'Kaltura_Client_Type_AssetParamsOutput',
		'KalturaAssetParamsOutputBaseFilter' => 'Kaltura_Client_Type_AssetParamsOutputBaseFilter',
		'KalturaAssetParamsOutputFilter' => 'Kaltura_Client_Type_AssetParamsOutputFilter',
		'KalturaAssetParamsResourceContainer' => 'Kaltura_Client_Type_AssetParamsResourceContainer',
		'KalturaAssetPropertiesCompareCondition' => 'Kaltura_Client_Type_AssetPropertiesCompareCondition',
		'KalturaAssetResource' => 'Kaltura_Client_Type_AssetResource',
		'KalturaAssetsParamsResourceContainers' => 'Kaltura_Client_Type_AssetsParamsResourceContainers',
		'KalturaAuthenticatedCondition' => 'Kaltura_Client_Type_AuthenticatedCondition',
		'KalturaBaseEntry' => 'Kaltura_Client_Type_BaseEntry',
		'KalturaBaseEntryBaseFilter' => 'Kaltura_Client_Type_BaseEntryBaseFilter',
		'KalturaBaseEntryFilter' => 'Kaltura_Client_Type_BaseEntryFilter',
		'KalturaBaseEntryListResponse' => 'Kaltura_Client_Type_BaseEntryListResponse',
		'KalturaBaseRestriction' => 'Kaltura_Client_Type_BaseRestriction',
		'KalturaBaseSyndicationFeed' => 'Kaltura_Client_Type_BaseSyndicationFeed',
		'KalturaBaseSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_BaseSyndicationFeedBaseFilter',
		'KalturaBaseSyndicationFeedFilter' => 'Kaltura_Client_Type_BaseSyndicationFeedFilter',
		'KalturaBaseSyndicationFeedListResponse' => 'Kaltura_Client_Type_BaseSyndicationFeedListResponse',
		'KalturaBatchJobBaseFilter' => 'Kaltura_Client_Type_BatchJobBaseFilter',
		'KalturaBatchJobFilter' => 'Kaltura_Client_Type_BatchJobFilter',
		'KalturaBatchJobFilterExt' => 'Kaltura_Client_Type_BatchJobFilterExt',
		'KalturaBooleanField' => 'Kaltura_Client_Type_BooleanField',
		'KalturaBooleanValue' => 'Kaltura_Client_Type_BooleanValue',
		'KalturaBulkUpload' => 'Kaltura_Client_Type_BulkUpload',
		'KalturaBulkUploadBaseFilter' => 'Kaltura_Client_Type_BulkUploadBaseFilter',
		'KalturaBulkUploadFilter' => 'Kaltura_Client_Type_BulkUploadFilter',
		'KalturaBulkUploadListResponse' => 'Kaltura_Client_Type_BulkUploadListResponse',
		'KalturaBulkUploadPluginData' => 'Kaltura_Client_Type_BulkUploadPluginData',
		'KalturaBulkUploadResult' => 'Kaltura_Client_Type_BulkUploadResult',
		'KalturaBulkUploadResultCategory' => 'Kaltura_Client_Type_BulkUploadResultCategory',
		'KalturaBulkUploadResultCategoryUser' => 'Kaltura_Client_Type_BulkUploadResultCategoryUser',
		'KalturaBulkUploadResultEntry' => 'Kaltura_Client_Type_BulkUploadResultEntry',
		'KalturaBulkUploadResultUser' => 'Kaltura_Client_Type_BulkUploadResultUser',
		'KalturaCEError' => 'Kaltura_Client_Type_CEError',
		'KalturaCategory' => 'Kaltura_Client_Type_Category',
		'KalturaCategoryBaseFilter' => 'Kaltura_Client_Type_CategoryBaseFilter',
		'KalturaCategoryEntry' => 'Kaltura_Client_Type_CategoryEntry',
		'KalturaCategoryEntryAdvancedFilter' => 'Kaltura_Client_Type_CategoryEntryAdvancedFilter',
		'KalturaCategoryEntryBaseFilter' => 'Kaltura_Client_Type_CategoryEntryBaseFilter',
		'KalturaCategoryEntryFilter' => 'Kaltura_Client_Type_CategoryEntryFilter',
		'KalturaCategoryEntryListResponse' => 'Kaltura_Client_Type_CategoryEntryListResponse',
		'KalturaCategoryFilter' => 'Kaltura_Client_Type_CategoryFilter',
		'KalturaCategoryListResponse' => 'Kaltura_Client_Type_CategoryListResponse',
		'KalturaCategoryUser' => 'Kaltura_Client_Type_CategoryUser',
		'KalturaCategoryUserBaseFilter' => 'Kaltura_Client_Type_CategoryUserBaseFilter',
		'KalturaCategoryUserFilter' => 'Kaltura_Client_Type_CategoryUserFilter',
		'KalturaCategoryUserListResponse' => 'Kaltura_Client_Type_CategoryUserListResponse',
		'KalturaClientNotification' => 'Kaltura_Client_Type_ClientNotification',
		'KalturaClipAttributes' => 'Kaltura_Client_Type_ClipAttributes',
		'KalturaCompareCondition' => 'Kaltura_Client_Type_CompareCondition',
		'KalturaCondition' => 'Kaltura_Client_Type_Condition',
		'KalturaContentResource' => 'Kaltura_Client_Type_ContentResource',
		'KalturaContext' => 'Kaltura_Client_Type_Context',
		'KalturaControlPanelCommandBaseFilter' => 'Kaltura_Client_Type_ControlPanelCommandBaseFilter',
		'KalturaControlPanelCommandFilter' => 'Kaltura_Client_Type_ControlPanelCommandFilter',
		'KalturaConversionAttribute' => 'Kaltura_Client_Type_ConversionAttribute',
		'KalturaConversionProfile' => 'Kaltura_Client_Type_ConversionProfile',
		'KalturaConversionProfileAssetParams' => 'Kaltura_Client_Type_ConversionProfileAssetParams',
		'KalturaConversionProfileAssetParamsBaseFilter' => 'Kaltura_Client_Type_ConversionProfileAssetParamsBaseFilter',
		'KalturaConversionProfileAssetParamsFilter' => 'Kaltura_Client_Type_ConversionProfileAssetParamsFilter',
		'KalturaConversionProfileAssetParamsListResponse' => 'Kaltura_Client_Type_ConversionProfileAssetParamsListResponse',
		'KalturaConversionProfileBaseFilter' => 'Kaltura_Client_Type_ConversionProfileBaseFilter',
		'KalturaConversionProfileFilter' => 'Kaltura_Client_Type_ConversionProfileFilter',
		'KalturaConversionProfileListResponse' => 'Kaltura_Client_Type_ConversionProfileListResponse',
		'KalturaCountryCondition' => 'Kaltura_Client_Type_CountryCondition',
		'KalturaCountryContextField' => 'Kaltura_Client_Type_CountryContextField',
		'KalturaCountryRestriction' => 'Kaltura_Client_Type_CountryRestriction',
		'KalturaCropDimensions' => 'Kaltura_Client_Type_CropDimensions',
		'KalturaDataCenterContentResource' => 'Kaltura_Client_Type_DataCenterContentResource',
		'KalturaDataEntry' => 'Kaltura_Client_Type_DataEntry',
		'KalturaDataEntryBaseFilter' => 'Kaltura_Client_Type_DataEntryBaseFilter',
		'KalturaDataEntryFilter' => 'Kaltura_Client_Type_DataEntryFilter',
		'KalturaDataListResponse' => 'Kaltura_Client_Type_DataListResponse',
		'KalturaDirectoryRestriction' => 'Kaltura_Client_Type_DirectoryRestriction',
		'KalturaDocumentEntry' => 'Kaltura_Client_Document_Type_DocumentEntry',
		'KalturaDocumentEntryBaseFilter' => 'Kaltura_Client_Document_Type_DocumentEntryBaseFilter',
		'KalturaDocumentEntryFilter' => 'Kaltura_Client_Document_Type_DocumentEntryFilter',
		'KalturaDocumentListResponse' => 'Kaltura_Client_Document_Type_DocumentListResponse',
		'KalturaEmailIngestionProfile' => 'Kaltura_Client_Type_EmailIngestionProfile',
		'KalturaEndUserReportInputFilter' => 'Kaltura_Client_Type_EndUserReportInputFilter',
		'KalturaEntryContext' => 'Kaltura_Client_Type_EntryContext',
		'KalturaEntryContextDataParams' => 'Kaltura_Client_Type_EntryContextDataParams',
		'KalturaEntryContextDataResult' => 'Kaltura_Client_Type_EntryContextDataResult',
		'KalturaEntryResource' => 'Kaltura_Client_Type_EntryResource',
		'KalturaEvalBooleanField' => 'Kaltura_Client_Type_EvalBooleanField',
		'KalturaEvalStringField' => 'Kaltura_Client_Type_EvalStringField',
		'KalturaFeatureStatus' => 'Kaltura_Client_Type_FeatureStatus',
		'KalturaFeatureStatusListResponse' => 'Kaltura_Client_Type_FeatureStatusListResponse',
		'KalturaFieldCompareCondition' => 'Kaltura_Client_Type_FieldCompareCondition',
		'KalturaFieldMatchCondition' => 'Kaltura_Client_Type_FieldMatchCondition',
		'KalturaFileSyncResource' => 'Kaltura_Client_Type_FileSyncResource',
		'KalturaFilter' => 'Kaltura_Client_Type_Filter',
		'KalturaFilterPager' => 'Kaltura_Client_Type_FilterPager',
		'KalturaFlavorAsset' => 'Kaltura_Client_Type_FlavorAsset',
		'KalturaFlavorAssetBaseFilter' => 'Kaltura_Client_Type_FlavorAssetBaseFilter',
		'KalturaFlavorAssetFilter' => 'Kaltura_Client_Type_FlavorAssetFilter',
		'KalturaFlavorAssetListResponse' => 'Kaltura_Client_Type_FlavorAssetListResponse',
		'KalturaFlavorAssetWithParams' => 'Kaltura_Client_Type_FlavorAssetWithParams',
		'KalturaFlavorParams' => 'Kaltura_Client_Type_FlavorParams',
		'KalturaFlavorParamsBaseFilter' => 'Kaltura_Client_Type_FlavorParamsBaseFilter',
		'KalturaFlavorParamsFilter' => 'Kaltura_Client_Type_FlavorParamsFilter',
		'KalturaFlavorParamsListResponse' => 'Kaltura_Client_Type_FlavorParamsListResponse',
		'KalturaFlavorParamsOutput' => 'Kaltura_Client_Type_FlavorParamsOutput',
		'KalturaFlavorParamsOutputBaseFilter' => 'Kaltura_Client_Type_FlavorParamsOutputBaseFilter',
		'KalturaFlavorParamsOutputFilter' => 'Kaltura_Client_Type_FlavorParamsOutputFilter',
		'KalturaFlavorParamsOutputListResponse' => 'Kaltura_Client_Type_FlavorParamsOutputListResponse',
		'KalturaGenericSyndicationFeed' => 'Kaltura_Client_Type_GenericSyndicationFeed',
		'KalturaGenericSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_GenericSyndicationFeedBaseFilter',
		'KalturaGenericSyndicationFeedFilter' => 'Kaltura_Client_Type_GenericSyndicationFeedFilter',
		'KalturaGenericXsltSyndicationFeed' => 'Kaltura_Client_Type_GenericXsltSyndicationFeed',
		'KalturaGenericXsltSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_GenericXsltSyndicationFeedBaseFilter',
		'KalturaGenericXsltSyndicationFeedFilter' => 'Kaltura_Client_Type_GenericXsltSyndicationFeedFilter',
		'KalturaGoogleVideoSyndicationFeed' => 'Kaltura_Client_Type_GoogleVideoSyndicationFeed',
		'KalturaGoogleVideoSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_GoogleVideoSyndicationFeedBaseFilter',
		'KalturaGoogleVideoSyndicationFeedFilter' => 'Kaltura_Client_Type_GoogleVideoSyndicationFeedFilter',
		'KalturaITunesSyndicationFeed' => 'Kaltura_Client_Type_ITunesSyndicationFeed',
		'KalturaITunesSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_ITunesSyndicationFeedBaseFilter',
		'KalturaITunesSyndicationFeedFilter' => 'Kaltura_Client_Type_ITunesSyndicationFeedFilter',
		'KalturaIndexAdvancedFilter' => 'Kaltura_Client_Type_IndexAdvancedFilter',
		'KalturaIntegerField' => 'Kaltura_Client_Type_IntegerField',
		'KalturaIntegerValue' => 'Kaltura_Client_Type_IntegerValue',
		'KalturaIpAddressCondition' => 'Kaltura_Client_Type_IpAddressCondition',
		'KalturaIpAddressContextField' => 'Kaltura_Client_Type_IpAddressContextField',
		'KalturaIpAddressRestriction' => 'Kaltura_Client_Type_IpAddressRestriction',
		'KalturaKeyValue' => 'Kaltura_Client_Type_KeyValue',
		'KalturaLiveStreamAdminEntry' => 'Kaltura_Client_Type_LiveStreamAdminEntry',
		'KalturaLiveStreamAdminEntryBaseFilter' => 'Kaltura_Client_Type_LiveStreamAdminEntryBaseFilter',
		'KalturaLiveStreamAdminEntryFilter' => 'Kaltura_Client_Type_LiveStreamAdminEntryFilter',
		'KalturaLiveStreamBitrate' => 'Kaltura_Client_Type_LiveStreamBitrate',
		'KalturaLiveStreamEntry' => 'Kaltura_Client_Type_LiveStreamEntry',
		'KalturaLiveStreamEntryBaseFilter' => 'Kaltura_Client_Type_LiveStreamEntryBaseFilter',
		'KalturaLiveStreamEntryFilter' => 'Kaltura_Client_Type_LiveStreamEntryFilter',
		'KalturaLiveStreamListResponse' => 'Kaltura_Client_Type_LiveStreamListResponse',
		'KalturaMatchCondition' => 'Kaltura_Client_Type_MatchCondition',
		'KalturaMediaEntry' => 'Kaltura_Client_Type_MediaEntry',
		'KalturaMediaEntryBaseFilter' => 'Kaltura_Client_Type_MediaEntryBaseFilter',
		'KalturaMediaEntryFilter' => 'Kaltura_Client_Type_MediaEntryFilter',
		'KalturaMediaEntryFilterForPlaylist' => 'Kaltura_Client_Type_MediaEntryFilterForPlaylist',
		'KalturaMediaFlavorParams' => 'Kaltura_Client_Type_MediaFlavorParams',
		'KalturaMediaFlavorParamsBaseFilter' => 'Kaltura_Client_Type_MediaFlavorParamsBaseFilter',
		'KalturaMediaFlavorParamsFilter' => 'Kaltura_Client_Type_MediaFlavorParamsFilter',
		'KalturaMediaFlavorParamsOutput' => 'Kaltura_Client_Type_MediaFlavorParamsOutput',
		'KalturaMediaFlavorParamsOutputBaseFilter' => 'Kaltura_Client_Type_MediaFlavorParamsOutputBaseFilter',
		'KalturaMediaFlavorParamsOutputFilter' => 'Kaltura_Client_Type_MediaFlavorParamsOutputFilter',
		'KalturaMediaInfo' => 'Kaltura_Client_Type_MediaInfo',
		'KalturaMediaInfoBaseFilter' => 'Kaltura_Client_Type_MediaInfoBaseFilter',
		'KalturaMediaInfoFilter' => 'Kaltura_Client_Type_MediaInfoFilter',
		'KalturaMediaInfoListResponse' => 'Kaltura_Client_Type_MediaInfoListResponse',
		'KalturaMediaListResponse' => 'Kaltura_Client_Type_MediaListResponse',
		'KalturaMixEntry' => 'Kaltura_Client_Type_MixEntry',
		'KalturaMixEntryBaseFilter' => 'Kaltura_Client_Type_MixEntryBaseFilter',
		'KalturaMixEntryFilter' => 'Kaltura_Client_Type_MixEntryFilter',
		'KalturaMixListResponse' => 'Kaltura_Client_Type_MixListResponse',
		'KalturaModerationFlag' => 'Kaltura_Client_Type_ModerationFlag',
		'KalturaModerationFlagListResponse' => 'Kaltura_Client_Type_ModerationFlagListResponse',
		'KalturaObjectIdField' => 'Kaltura_Client_Type_ObjectIdField',
		'KalturaOperationAttributes' => 'Kaltura_Client_Type_OperationAttributes',
		'KalturaOperationResource' => 'Kaltura_Client_Type_OperationResource',
		'KalturaPartner' => 'Kaltura_Client_Type_Partner',
		'KalturaPartnerBaseFilter' => 'Kaltura_Client_Type_PartnerBaseFilter',
		'KalturaPartnerFilter' => 'Kaltura_Client_Type_PartnerFilter',
		'KalturaPartnerListResponse' => 'Kaltura_Client_Type_PartnerListResponse',
		'KalturaPartnerStatistics' => 'Kaltura_Client_Type_PartnerStatistics',
		'KalturaPartnerUsage' => 'Kaltura_Client_Type_PartnerUsage',
		'KalturaPermission' => 'Kaltura_Client_Type_Permission',
		'KalturaPermissionBaseFilter' => 'Kaltura_Client_Type_PermissionBaseFilter',
		'KalturaPermissionFilter' => 'Kaltura_Client_Type_PermissionFilter',
		'KalturaPermissionItem' => 'Kaltura_Client_Type_PermissionItem',
		'KalturaPermissionItemBaseFilter' => 'Kaltura_Client_Type_PermissionItemBaseFilter',
		'KalturaPermissionItemFilter' => 'Kaltura_Client_Type_PermissionItemFilter',
		'KalturaPermissionItemListResponse' => 'Kaltura_Client_Type_PermissionItemListResponse',
		'KalturaPermissionListResponse' => 'Kaltura_Client_Type_PermissionListResponse',
		'KalturaPlayableEntry' => 'Kaltura_Client_Type_PlayableEntry',
		'KalturaPlayableEntryBaseFilter' => 'Kaltura_Client_Type_PlayableEntryBaseFilter',
		'KalturaPlayableEntryFilter' => 'Kaltura_Client_Type_PlayableEntryFilter',
		'KalturaPlaylist' => 'Kaltura_Client_Type_Playlist',
		'KalturaPlaylistBaseFilter' => 'Kaltura_Client_Type_PlaylistBaseFilter',
		'KalturaPlaylistFilter' => 'Kaltura_Client_Type_PlaylistFilter',
		'KalturaPlaylistListResponse' => 'Kaltura_Client_Type_PlaylistListResponse',
		'KalturaPreviewRestriction' => 'Kaltura_Client_Type_PreviewRestriction',
		'KalturaRegexCondition' => 'Kaltura_Client_Type_RegexCondition',
		'KalturaRemotePath' => 'Kaltura_Client_Type_RemotePath',
		'KalturaRemotePathListResponse' => 'Kaltura_Client_Type_RemotePathListResponse',
		'KalturaRemoteStorageResource' => 'Kaltura_Client_Type_RemoteStorageResource',
		'KalturaRemoteStorageResources' => 'Kaltura_Client_Type_RemoteStorageResources',
		'KalturaReportBaseFilter' => 'Kaltura_Client_Type_ReportBaseFilter',
		'KalturaReportBaseTotal' => 'Kaltura_Client_Type_ReportBaseTotal',
		'KalturaReportFilter' => 'Kaltura_Client_Type_ReportFilter',
		'KalturaReportGraph' => 'Kaltura_Client_Type_ReportGraph',
		'KalturaReportInputBaseFilter' => 'Kaltura_Client_Type_ReportInputBaseFilter',
		'KalturaReportInputFilter' => 'Kaltura_Client_Type_ReportInputFilter',
		'KalturaReportResponse' => 'Kaltura_Client_Type_ReportResponse',
		'KalturaReportTable' => 'Kaltura_Client_Type_ReportTable',
		'KalturaReportTotal' => 'Kaltura_Client_Type_ReportTotal',
		'KalturaResource' => 'Kaltura_Client_Type_Resource',
		'KalturaRule' => 'Kaltura_Client_Type_Rule',
		'KalturaSearch' => 'Kaltura_Client_Type_Search',
		'KalturaSearchAuthData' => 'Kaltura_Client_Type_SearchAuthData',
		'KalturaSearchComparableCondition' => 'Kaltura_Client_Type_SearchComparableCondition',
		'KalturaSearchCondition' => 'Kaltura_Client_Type_SearchCondition',
		'KalturaSearchItem' => 'Kaltura_Client_Type_SearchItem',
		'KalturaSearchOperator' => 'Kaltura_Client_Type_SearchOperator',
		'KalturaSearchResult' => 'Kaltura_Client_Type_SearchResult',
		'KalturaSearchResultResponse' => 'Kaltura_Client_Type_SearchResultResponse',
		'KalturaServerFileResource' => 'Kaltura_Client_Type_ServerFileResource',
		'KalturaSessionInfo' => 'Kaltura_Client_Type_SessionInfo',
		'KalturaSessionRestriction' => 'Kaltura_Client_Type_SessionRestriction',
		'KalturaSiteCondition' => 'Kaltura_Client_Type_SiteCondition',
		'KalturaSiteRestriction' => 'Kaltura_Client_Type_SiteRestriction',
		'KalturaSshUrlResource' => 'Kaltura_Client_Type_SshUrlResource',
		'KalturaStartWidgetSessionResponse' => 'Kaltura_Client_Type_StartWidgetSessionResponse',
		'KalturaStatsEvent' => 'Kaltura_Client_Type_StatsEvent',
		'KalturaStatsKmcEvent' => 'Kaltura_Client_Type_StatsKmcEvent',
		'KalturaStorageProfile' => 'Kaltura_Client_Type_StorageProfile',
		'KalturaStorageProfileBaseFilter' => 'Kaltura_Client_Type_StorageProfileBaseFilter',
		'KalturaStorageProfileFilter' => 'Kaltura_Client_Type_StorageProfileFilter',
		'KalturaStorageProfileListResponse' => 'Kaltura_Client_Type_StorageProfileListResponse',
		'KalturaString' => 'Kaltura_Client_Type_String',
		'KalturaStringField' => 'Kaltura_Client_Type_StringField',
		'KalturaStringResource' => 'Kaltura_Client_Type_StringResource',
		'KalturaStringValue' => 'Kaltura_Client_Type_StringValue',
		'KalturaSyndicationFeedEntryCount' => 'Kaltura_Client_Type_SyndicationFeedEntryCount',
		'KalturaThumbAsset' => 'Kaltura_Client_Type_ThumbAsset',
		'KalturaThumbAssetBaseFilter' => 'Kaltura_Client_Type_ThumbAssetBaseFilter',
		'KalturaThumbAssetFilter' => 'Kaltura_Client_Type_ThumbAssetFilter',
		'KalturaThumbAssetListResponse' => 'Kaltura_Client_Type_ThumbAssetListResponse',
		'KalturaThumbParams' => 'Kaltura_Client_Type_ThumbParams',
		'KalturaThumbParamsBaseFilter' => 'Kaltura_Client_Type_ThumbParamsBaseFilter',
		'KalturaThumbParamsFilter' => 'Kaltura_Client_Type_ThumbParamsFilter',
		'KalturaThumbParamsListResponse' => 'Kaltura_Client_Type_ThumbParamsListResponse',
		'KalturaThumbParamsOutput' => 'Kaltura_Client_Type_ThumbParamsOutput',
		'KalturaThumbParamsOutputBaseFilter' => 'Kaltura_Client_Type_ThumbParamsOutputBaseFilter',
		'KalturaThumbParamsOutputFilter' => 'Kaltura_Client_Type_ThumbParamsOutputFilter',
		'KalturaThumbParamsOutputListResponse' => 'Kaltura_Client_Type_ThumbParamsOutputListResponse',
		'KalturaTimeContextField' => 'Kaltura_Client_Type_TimeContextField',
		'KalturaTubeMogulSyndicationFeed' => 'Kaltura_Client_Type_TubeMogulSyndicationFeed',
		'KalturaTubeMogulSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_TubeMogulSyndicationFeedBaseFilter',
		'KalturaTubeMogulSyndicationFeedFilter' => 'Kaltura_Client_Type_TubeMogulSyndicationFeedFilter',
		'KalturaUiConf' => 'Kaltura_Client_Type_UiConf',
		'KalturaUiConfBaseFilter' => 'Kaltura_Client_Type_UiConfBaseFilter',
		'KalturaUiConfFilter' => 'Kaltura_Client_Type_UiConfFilter',
		'KalturaUiConfListResponse' => 'Kaltura_Client_Type_UiConfListResponse',
		'KalturaUiConfTypeInfo' => 'Kaltura_Client_Type_UiConfTypeInfo',
		'KalturaUploadResponse' => 'Kaltura_Client_Type_UploadResponse',
		'KalturaUploadToken' => 'Kaltura_Client_Type_UploadToken',
		'KalturaUploadTokenBaseFilter' => 'Kaltura_Client_Type_UploadTokenBaseFilter',
		'KalturaUploadTokenFilter' => 'Kaltura_Client_Type_UploadTokenFilter',
		'KalturaUploadTokenListResponse' => 'Kaltura_Client_Type_UploadTokenListResponse',
		'KalturaUploadedFileTokenResource' => 'Kaltura_Client_Type_UploadedFileTokenResource',
		'KalturaUrlResource' => 'Kaltura_Client_Type_UrlResource',
		'KalturaUser' => 'Kaltura_Client_Type_User',
		'KalturaUserAgentCondition' => 'Kaltura_Client_Type_UserAgentCondition',
		'KalturaUserAgentContextField' => 'Kaltura_Client_Type_UserAgentContextField',
		'KalturaUserAgentRestriction' => 'Kaltura_Client_Type_UserAgentRestriction',
		'KalturaUserBaseFilter' => 'Kaltura_Client_Type_UserBaseFilter',
		'KalturaUserEmailContextField' => 'Kaltura_Client_Type_UserEmailContextField',
		'KalturaUserFilter' => 'Kaltura_Client_Type_UserFilter',
		'KalturaUserListResponse' => 'Kaltura_Client_Type_UserListResponse',
		'KalturaUserLoginDataBaseFilter' => 'Kaltura_Client_Type_UserLoginDataBaseFilter',
		'KalturaUserLoginDataFilter' => 'Kaltura_Client_Type_UserLoginDataFilter',
		'KalturaUserRole' => 'Kaltura_Client_Type_UserRole',
		'KalturaUserRoleBaseFilter' => 'Kaltura_Client_Type_UserRoleBaseFilter',
		'KalturaUserRoleFilter' => 'Kaltura_Client_Type_UserRoleFilter',
		'KalturaUserRoleListResponse' => 'Kaltura_Client_Type_UserRoleListResponse',
		'KalturaValue' => 'Kaltura_Client_Type_Value',
		'KalturaWebcamTokenResource' => 'Kaltura_Client_Type_WebcamTokenResource',
		'KalturaWidget' => 'Kaltura_Client_Type_Widget',
		'KalturaWidgetBaseFilter' => 'Kaltura_Client_Type_WidgetBaseFilter',
		'KalturaWidgetFilter' => 'Kaltura_Client_Type_WidgetFilter',
		'KalturaWidgetListResponse' => 'Kaltura_Client_Type_WidgetListResponse',
		'KalturaYahooSyndicationFeed' => 'Kaltura_Client_Type_YahooSyndicationFeed',
		'KalturaYahooSyndicationFeedBaseFilter' => 'Kaltura_Client_Type_YahooSyndicationFeedBaseFilter',
		'KalturaYahooSyndicationFeedFilter' => 'Kaltura_Client_Type_YahooSyndicationFeedFilter',
	);
	
	public static function getZendType($kalturaType)
	{
		if(isset(self::$map[$kalturaType]))
			return self::$map[$kalturaType];
		return null;
	}
}
