<?php
/**
 * @package plugins.facebookDistribution
 * @subpackage model.enum
 */
interface FacebookDistributionField extends BaseEnum
{
	const TITLE = 'TITLE';
	const DESCRIPTION = 'DESCRIPTION';
	const TRIGGER_BASIC_FIELDS = 'BASIC_TRIGGER_FIELDS';
	const CALL_TO_ACTION_TYPE = 'CALL_TO_ACTION_TYPE';
	const CALL_TO_ACTION_LINK = 'CALL_TO_ACTION_LINK';
	const CALL_TO_ACTION_LINK_CAPTION = 'CALL_TO_ACTION_LINK_CAPTION';
	const CALL_TO_ACTION_TYPE_VALID_VALUES = 'CALL_TO_ACTION_TYPE_VALID_VALUES';
	const PLACE = 'PLACE';
	const TAGS = 'TAGS';
	const FEED_TARGETING = 'FEED_TARGETING';
	const SCHEDULE_PUBLISHING_TIME = 'SCHEDULE_PUBLISHING_TIME';
	const TARGETING_COUNTRIES = 'TARGETING_COUNTRIES'; //list
	const TARGETING_REGIONS = 'TARGETING_REGIONS'; //list
	const TARGETING_CITIES = 'TARGETING_CITIES'; //list
	const TARGETING_ZIP_CODES = 'TARGETING_ZIP_CODES'; //list
	const TARGETING_EXCLUDED_COUNTRIES = 'TARGETING_EXCLUDED_COUNTRIES';//list
	const TARGETING_EXCLUDED_REGIONS = 'TARGETING_EXCLUDED_REGIONS';//list
	const TARGETING_EXCLUDED_CITIES = 'TARGETING_EXCLUDED_CITIES';//list
	const TARGETING_EXCLUDED_ZIPCODES = 'TARGETING_EXCLUDED_ZIPCODES';//list
	const TARGETING_TIMEZONES = 'TARGETING_TIMEZONES';//list
	const TARGETING_AGE_MIN = 'TARGETING_AGE_MIN';
	const TARGETING_AGE_MAX = 'TARGETING_AGE_MAX';
	const TARGETING_GENDERS = 'TARGETING_GENDERS';//list
	const TARGETING_LOCALES = 'TARGETING_LOCALES';//list
	const FEED_TARGETING_COUNTRIES = 'FEED_TARGETING_COUNTRIES'; //list
	const FEED_TARGETING_REGIONS = 'FEED_TARGETING_REGIONS'; //list
	const FEED_TARGETING_CITIES = 'FEED_TARGETING_CITIES'; //list
	const FEED_TARGETING_AGE_MIN = 'FEED_TARGETING_AGE_MIN';
	const FEED_TARGETING_AGE_MAX = 'FEED_TARGETING_AGE_MAX';
	const FEED_TARGETING_GENDERS = 'FEED_TARGETING_GENDERS';//list
	const FEED_TARGETING_LOCALES = 'FEED_TARGETING_LOCALES';//list
	const FEED_TARGETING_INTERESTED_IN = 'FEED_TARGETING_INTERESTED_IN';//list
	const FEED_TARGETING_EDUCATION_STATUSES = 'FEED_TARGETING_EDUCATION_STATUSES';//list
	const FEED_TARGETING_RELATIONSHIP_STATUSES = 'FEED_TARGETING_RELATIONSHIP_STATUSES';//list
	const FEED_TARGETING_COLLEGE_YEARS = 'FEED_TARGETING_COLLEGE_YEARS';//list
	const FEED_TARGETING_INTERESTS = 'FEED_TARGETING_INTERESTS';//list
	const FEED_TARGETING_RELEVANT_UNTIL = 'FEED_TARGETING_RELEVANT_UNTIL';
}