<fieldset class="tvinci-tag">
	<legend>Tvinci Tags</legend>
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($subForm->getName()); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<a class="add-tag" href="javascript:;" onclick="addDistributionTag(this);" >+ Add Tag</a>
</fieldset>

<style type="text/css">
	#frmDistributionProfileConfig .tvinci-tag { padding: 10px; }
	#frmDistributionProfileConfig .tvinci-tag span.rule { font-size: 14px; font-weight: bold; }
	#frmDistributionProfileConfig .tvinci-tag label { display: block; padding: 4px 0; }
	#frmDistributionProfileConfig .tvinci-tag fieldset { height: auto; margin: 6px 0; padding: 10px; border: 1px solid #CCCCCC; }
	#frmDistributionProfileConfig .tvinci-tag .add-condition,
	#frmDistributionProfileConfig .tvinci-tag .remove-condition { margin: 4px 0; }
	#frmDistributionProfileConfig .tvinci-tag .add-condition { float: left; }
	#frmDistributionProfileConfig .tvinci-tag .remove-condition { float: right; }
	#frmDistributionProfileConfig .tvinci-tag .remove-property { float: right; }
</style>

<script type="text/javascript">
	
	function addDistributionTag(target) {
		<?php $subForm = new Form_TvinciTagSubForm(); ?>
		<?php $subForm->setElementsBelongTo('tvinci_distribution_tags_REPLACE_RANDOM'); ?>
		var template = '<?php echo str_replace(array("\n", "\r"), '', $subForm->__toString()); ?>';
		var belongsRand = new Date().getTime();
		template = template.replace(/REPLACE_RANDOM/g, belongsRand);
		jQuery(target).before(template);
		jQuery(target).parent().find('[name=belongs]').val('tvinci_distribution_tags_'+belongsRand);
	}
	
</script>