<fieldset >
	<legend>Tag</legend>
	<?php echo $this->element->getElement('tag_name'); ?></br>
	<?php echo $this->element->getElement('tag_extension'); ?><br/>
	<?php echo $this->element->getElement('tag_protocol'); ?><br/>
	<?php echo $this->element->getElement('tag_format'); ?><br/>
	<?php echo $this->element->getElement('tag_file_name'); ?><br/>
	<?php echo $this->element->getElement('tag_ippvmodule'); ?><br/>
	<input type="hidden" name="belongs" value="<?php echo $this->element->getElementsBelongTo(); ?>" />
	<a class="remove-condition" href="javascript:;" onclick="$(this).parent().remove(); ">Remove</a>
</fieldset>