<fieldset>
	<dt>
		<label>Authorize API Access</label>
	</dt>
	<dd>
		<input type="text" value="<?php echo $this->element->getValue(); ?>" id="api_authorize_url">
		<p class="description">Send this link to the person who has access to the KMC and the Tvinci channel. He should login using his KMC credentials and then authenticate at Google using his Google Account that is linked with his Tvinci channel. This authorization process is only required when using playlists.</p>
	</dd>
</fieldset>