<?php
/**
 * @package plugins.attUverseDistribution
 * @subpackage model.enum
 */ 
interface AttUverseDistributionField extends BaseEnum
{
	
	const CHANNEL_TITLE  = 'CHANNEL_TITLE';
	//item
	const ITEM_ENTRY_ID = 'ITEM_ENTRY_ID';
	const ITEM_CREATED_AT = 'ITEM_CREATED_AT';
	const ITEM_UPDATED_AT = 'ITEM_UPDATED_AT';
	const ITEM_START_DATE = 'ITEM_START_DATE';
	const ITEM_END_DATE = 'ITEM_END_DATE';
	const ITEM_TITLE = 'ITEM_TITLE';
	const ITEM_DESCRIPTION = 'ITEM_DESCRIPTION';
	const ITEM_TAGS = 'ITEM_TAGS';
	const ITEM_CATEGORIES = 'ITEM_CATEGORIES';
	//item metadata
	const ITEM_METADATA_SHORT_TITLE = 'ITEM_METADATA_SHORT_TITLE';
	const ITEM_METADATA_TUNEIN = 'ITEM_METADATA_TUNEIN';
	const ITEM_METADATA_CONTENT_RATING = 'ITEM_METADATA_CONTENT_RATING';
	const ITEM_METADATA_LEGAL_DISCLAIMER = 'ITEM_METADATA_LEGAL_DISCLAIMER';
	const ITEM_METADATA_GENRE = 'ITEM_METADATA_GENRE';
}