copy/y masks\masks.swf 123\123.swf
copy/y masks\masks.swf arrows\arrows.swf
copy/y masks\masks.swf collapsing_box\collapsing_box.swf
copy/y masks\masks.swf col_drop\col_drop.swf
copy/y masks\masks.swf corner_rollout\corner_rollout.swf
copy/y masks\masks.swf crazy_blocks\crazy_blocks.swf
copy/y masks\masks.swf curtains\curtains.swf
copy/y masks\masks.swf dripping_blood\dripping_blood.swf
copy/y masks\masks.swf filling_blocks\filling_blocks.swf
copy/y masks\masks.swf filling_blocks_diagonal\filling_blocks_diagonal.swf
copy/y masks\masks.swf filling_blocks_left\filling_blocks_left.swf
copy/y masks\masks.swf filling_bubbles\filling_bubbles.swf
copy/y masks\masks.swf filling_bubbles_diagonal\filling_bubbles_diagonal.swf
copy/y masks\masks.swf glowing_star\glowing_star.swf
copy/y masks\masks.swf heart\heart.swf
copy/y masks\masks.swf paintingBrush\paintingBrush.swf
copy/y masks\masks.swf squares_snake\squares_snake.swf
copy/y masks\masks.swf starSlide\starSlide.swf
copy/y masks\masks.swf surprising_bubbles\surprising_bubbles.swf
