<?php 
	$this->headLink()	->setIndent("	")
						->appendStylesheet($this->baseUrl('css/jquery-ui/smoothness/jquery-ui-1.7.2.custom.css'))
						->appendStylesheet($this->baseUrl('css/global.css'));
					 
	$this->headScript()	->setIndent("	")
						->prependFile($this->baseUrl('js/jquery-1.3.2.min.js'))
						->appendFile($this->baseUrl('js/jquery-ui-1.7.2.custom.min.js'))
						->appendFile($this->baseUrl('js/jquery.form.js'));
?>
<?php echo $this->doctype().PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Kaltura Admin Console</title>
<?php echo $this->headLink()->toString().PHP_EOL; ?>
<?php echo $this->headScript()->toString().PHP_EOL;?>
</head> 
<body id="<?php echo $this->cssId(); ?>">
<div id="kmcHeader">
	<div id="logo"></div>
	<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
		<?php echo $this->navigation()->menu()->renderMenu(null, array('maxDepth' => 0)); ?>
	<?php endif; ?>
	<div id="user_links">
		<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
			<span>Hi <?php echo Zend_Auth::getInstance()->getIdentity()->getUser()->firstName; ?></span><br />
			<!--
			<a href="javascript:alert('link to be provided')">Quick Start Guide</a> &nbsp;| &nbsp;
			<a href="javascript:alert('link to be provided')">Support</a> &nbsp;| &nbsp;
			-->
			<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), null, true); ?>">Logout</a>
		<?php endif; ?>
	</div>
</div>
<div id="sub-header">
	<a id="help">[?]</a>
	<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
		<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
			<?php echo $this->navigation()->menu()->renderMenu(null, array(
				'onlyActiveBranch' => true,
				'ulClass' => 'sub-navigation', 
				'minDepth' => 1, 
				'maxDepth' => 1
			)); ?>
		<?php endif; ?>
	<?php endif; ?>
</div>
<div id="wrapper">
	<?php echo $this->layout()->content ?>
</div>
</body>
</html>