<fieldset class="regex-rule">
	<legend>Rule</legend>
	<label>Regex: <?php echo $this->element->getElement('regex'); ?></label>
	<label>Description: <?php echo $this->element->getElement('description'); ?></label>
	<input type="hidden" name="belongs" value="<?php echo $this->element->getElementsBelongTo(); ?>" />
	<?php foreach($this->element->getSubForms() as $subForm): ?>
		<?php $subForm->setElementsBelongTo($this->element->getElementsBelongTo().'['.$subForm->getName().']'); ?>
		<?php echo $subForm; ?>
	<?php endforeach; ?>
	<a class="remove-condition" href="javascript:;" onclick="$(this).parent().remove(); ">Remove</a>
</fieldset>