<?php if($this->errMessage): ?>
	<div class="error"><?php echo $this->errMessage ?></div><br/>
<?php else: ?>
	<p><?php echo $this->translate('Here you can configure your maps'); ?></p>
<?php endif; ?>

<?php echo $this->filterForm; ?>
<?php echo $this->newConfigurationMapFolderForm; ?>
<div id="configuration_map_list_div" class="clear">
    <table>
        <thead>
        <tr>
            <th><?php echo $this->translate('Name'); ?></th>
            <th><?php echo $this->translate('Host'); ?></th>
            <th><?php echo $this->translate('Version'); ?></th>
            <th><?php echo $this->translate('Source Location'); ?></th>
            <th><?php echo $this->translate('Last Updated Date'); ?></th>
            <th><?php echo $this->translate('Actions'); ?></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="14">
				<?php echo $this->paginator; ?>
            </td>
        </tr>
        </tfoot>
        <tbody>
				<?php if($this->paginator)
				foreach ($this->paginator as /* Kaltura_Client_ConfMaps_Type_ConfMaps*/$configurationMap):?>
                <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
                <td><?php echo $configurationMap->name; ?></td>
	            <td><?php echo $configurationMap->relatedHost; ?></td>
	            <td><?php echo $configurationMap->version; ?></td>
	            <td><?php echo $this->enumTranslate('Kaltura_Client_Enum_ConfMapSourceLocation', $configurationMap->sourceLocation);?></td>
	            <td><?php echo date($this->translate('time format'), $configurationMap->lastUpdate); ?></td>
                <td>
		            <select class="options" onchange="doAction(this.value,'<?php echo $configurationMap->name; ?>', '<?php echo $configurationMap->relatedHost; ?>', '<?php echo $configurationMap->version; ?>')">
		                <option value=""><?php echo $this->translate('Select Action'); ?></option>
		                <option value="configureConfigurationMap"><?php echo $this->translate('Configure'); ?></option>
	                </select>
                </td>
            </tr>
		<?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">

	jQuery('#filter_type').change(function () {
		if (this.value == "none") {
			$("#filter_text").css("display", "none");
		}
		else {
			$("#filter_text").css("display", "inline");
			$("#filter_text input").focus();
			if (this.value == "free")
				$("div.help").show();
			else
				$("div.help").hide();
		}
	});

	jQuery('#filter_type').change();

	function doAction(action) {
		if (action && eval('typeof ' + action) == 'function')
		{
			f = eval(action);
			Array.prototype.shift.apply(arguments);
			f.apply(this, arguments);
		}
		jQuery('select.options').val('');
	}

	function configureConfigurationMap(configurationMapName, configurationMapHost, configurationMapVersion) {
		if (typeof configurationMapName == 'undefined') {
			alert('<?php echo $this->translate('Configuration Map Name not supplied'); ?>');
			return;
		}

		var configurationMapStr= '/configuration_map_name/' + encodeURIComponent(configurationMapName) + '/configuration_map_host/' + encodeURIComponent(configurationMapHost)  + '/configuration_map_version/' + configurationMapVersion + '/is_new/' + false;

		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'ConfigurationMapConfigureAction')); ?>' + configurationMapStr;

		jQuery('#configuration-map-configure-dialog').remove();
		dialogDiv = jQuery('<div id="configuration-map-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');

		dialogDiv.dialog({
			bgiframe: true,
			modal: true,
			resizable: false,
			width: 600,
			height: 600,
			title: '<?php echo $this->translate('Configuration Map'); ?>',
			buttons: {
				"SaveButton":{
					text:'<?php echo $this->translate('Save'); ?>',
					id: "saveButton",
					click: function () {
						jQuery('.ui-widget-overlay').css('z-index', 1003);
						jQuery('#loader').show();
						jQuery(this).find('#frmConfigurationMapConfigure').submit();
					}},
				'<?php echo $this->translate('Close'); ?>': function () {
					jQuery(this).dialog('close');
				}
			},
			close: function () {
				jQuery(this).dialog('destroy').remove();
			}
		});

		dialogDiv.load(
			url,
			null,
			function () {
				jQuery(this).find('#frmConfigurationMapConfigure').ajaxForm({
					success: loadConfigurationMapSuccess,
					iframe: true
				});
			}
		);
	}

	function viewConfigurationMap(configurationMapName, configurationMapHost, configurationMapVersion) {
		var configurationMapStr = '/configuration_map_name/' + encodeURIComponent(configurationMapName) + '/configuration_map_host/' + encodeURIComponent(configurationMapHost) + '/is_new/' + false + '/is_view/' + true;
		if (typeof configurationMapVersion != 'undefined')
		{
			if (configurationMapVersion == '' || isNaN(parseInt(configurationMapVersion)) || (parseInt(configurationMapVersion)) < 0)
			{
				alert('<?php echo $this->translate('Configuration Version should be a positive number'); ?>');
				return;
			}
			else
			{
				var configurationMapStr = configurationMapStr + '/configuration_map_version/' + configurationMapVersion;
			}
		}
		handleConfigurationAction(configurationMapStr, true);
	}

	function addNewConfigurationMap(configurationMapName, configurationMapHost) {
		var configurationMapStr = '/configuration_map_name/' + encodeURIComponent(configurationMapName) + '/configuration_map_host/' + encodeURIComponent(configurationMapHost) + '/is_new/' + true;
		handleConfigurationAction(configurationMapStr);
	}

	function handleConfigurationAction(configurationMapStr, isViewOnly){
		var url = '<?php echo $this->url(array('controller' => 'plugin', 'action' => 'ConfigurationMapConfigureAction')); ?>' + configurationMapStr;

		jQuery('#configuration-map-configure-dialog').remove();
		dialogDiv = jQuery('<div id="configuration-map-configure-dialog"><?php echo $this->translate('Loading...'); ?></div>').appendTo('body');

		var buttons = {};
		if (isViewOnly)
		{
			buttons = {
				'<?php echo $this->translate('Close'); ?>': function () {
					jQuery(this).dialog('close');
				}
			}
		}
		else {
			buttons = {
				'<?php echo $this->translate('Save'); ?>': function () {
					jQuery('.ui-widget-overlay').css('z-index', 1003);
					jQuery('#loader').show();
					jQuery(this).find('#frmConfigurationMapConfigure').submit();
				},
				'<?php echo $this->translate('Close'); ?>': function () {
					jQuery(this).dialog('close');
				}
			}
		}
		dialogDiv.dialog({
			bgiframe: true,
			modal: true,
			resizable: false,
			width: 600,
			height: 600,
			title: '<?php echo $this->translate('Configuration Map'); ?>',
			buttons: buttons,
			close: function () {
				jQuery(this).dialog('destroy').remove();
			}
		});

		dialogDiv.load(
			url,
			null,
			function () {
				jQuery(this).find('#frmConfigurationMapConfigure').ajaxForm({
					success: loadConfigurationMapSuccess,
					iframe: true
				});
			}
		);
	}

	function loadConfigurationMapSuccess(html) {
		if (jQuery(html).filter('#frmConfigurationMapConfigure').hasClass('valid')) {
			dialogDiv.dialog('close');
			if (jQuery('#frmPaginator1').length) {
				jQuery('#frmPaginator1').submit();
			}
			else {
				jQuery('#frmPartnerIdFilter').submit();
			}
		}
		jQuery('.ui-widget-overlay').css('z-index', 1000);
		jQuery('#loader').hide();
		jQuery('#frmConfigurationMapConfigure').replaceWith(html);
		jQuery('#frmConfigurationMapConfigure').ajaxForm({
			success: loadConfigurationMapSuccess,
			iframe: true
		});
	}

</script>
