<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file C:\opt\kaltura\app\alpha\config\runtime-conf.xml
return array (
  'datasources' => 
  array (
    'kaltura' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'phptype' => 'mysql',
        'database' => 'kaltura',
        'hostspec' => 'localhost',
        'username' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'kaltura',
  ),
  'log' => 
  array (
    'ident' => 'kaltura',
    'level' => '7',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'DrmProfileTableMap' => 'lib/model/map/DrmProfileTableMap.php',
    'DrmProfilePeer' => 'lib/model/DrmProfilePeer.php',
    'DrmProfile' => 'lib/model/DrmProfile.php',
    'DrmPolicyTableMap' => 'lib/model/map/DrmPolicyTableMap.php',
    'DrmPolicyPeer' => 'lib/model/DrmPolicyPeer.php',
    'DrmPolicy' => 'lib/model/DrmPolicy.php',
    'DrmDeviceTableMap' => 'lib/model/map/DrmDeviceTableMap.php',
    'DrmDevicePeer' => 'lib/model/DrmDevicePeer.php',
    'DrmDevice' => 'lib/model/DrmDevice.php',
    'DrmKeyTableMap' => 'lib/model/map/DrmKeyTableMap.php',
    'DrmKeyPeer' => 'lib/model/DrmKeyPeer.php',
    'DrmKey' => 'lib/model/DrmKey.php',
  ),
);