<?php
class kPermissionException extends kCoreException
{
	const PERMISSION_ITEM_NOT_FOUND = 'PERMISSION_ITEM_NOT_FOUND';
	
	const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';
	
	const PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND';
	
	const PERMISSION_ALREADY_CONTAINS_ITEM = 'PERMISSION_ALREADY_CONTAINS_ITEM';
	
	const ONLY_ONE_ROLE_PER_USER_ALLOWED = 'ONLY_ONE_ROLE_PER_USER_ALLOWED';
	
	const ROLE_ID_MISSING = 'ROLE_ID_MISSING';
}