<?php
class kUploadTokenException extends kCoreException
{
	const UPLOAD_TOKEN_FILE_NAME_IS_MISSING_FOR_UPLOADED_FILE = "UPLOAD_TOKEN_FILE_NAME_IS_MISSING_FOR_UPLOADED_FILE";
	
	const UPLOAD_TOKEN_FILE_IS_NOT_VALID = "UPLOAD_TOKEN_FILE_IS_NOT_VALID"; 
	
	const UPLOAD_TOKEN_FAILED_TO_MOVE_UPLOADED_FILE = "UPLOAD_TOKEN_FAILED_TO_MOVE_UPLOADED_FILE";
	
	const UPLOAD_TOKEN_UPLOAD_ERROR_OCCURRED = "UPLOAD_TOKEN_UPLOAD_ERROR_OCCURRED";
	
	const UPLOAD_TOKEN_FILE_NOT_FOUND_FOR_RESUME = "UPLOAD_TOKEN_FILE_NOT_FOUND_FOR_RESUME";
	
	const UPLOAD_TOKEN_INVALID_STATUS = "UPLOAD_TOKEN_INVALID_STATUS";
	
	const UPLOAD_TOKEN_NOT_FOUND = "UPLOAD_TOKEN_NOT_FOUND";
	
	const UPLOAD_TOKEN_RESUMING_NOT_ALLOWED = "UPLOAD_TOKEN_RESUMING_NOT_ALLOWED";
	
	const UPLOAD_TOKEN_RESUMING_INVALID_POSITION = "UPLOAD_TOKEN_RESUMING_INVALID_POSITION";
}