<?php
class kUserLoginException extends kCoreException
{
	const LOGIN_DATA_NOT_FOUND = 'LOGIN_DATA_NOT_FOUND';
	
	const WRONG_OLD_PASSWORD = 'WRONG_OLD_PASSWORD';
	
	const PASSWORD_STRUCTURE_INVALID = 'PASSWORD_STRUCTURE_INVALID';
	
	const PASSWORD_ALREADY_USED = 'PASSWORD_ALREADY_USED';
	
	const NEW_PASSWORD_HASH_KEY_INVALID = 'NEW_PASSWORD_HASH_KEY_INVALID';
	
	const NEW_PASSWORD_HASH_KEY_EXPIRED = 'NEW_PASSWORD_HASH_KEY_EXPIRED';
	
	const LOGIN_RETRIES_EXCEEDED = 'LOGIN_RETRIES_EXCEEDED';
	
	const LOGIN_BLOCKED = 'LOGIN_BLOCKED';
	
	const PASSWORD_EXPIRED = 'PASSWORD_EXPIRED';
}